In [81]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [82]:
import pandas as pd

In [83]:
df = pd.read_csv('/content/drive/MyDrive/문화관광 빅데이터 공모전/전처리/한국농어촌공사_농촌관광등급결정현황_20220902.csv', encoding='cp949')
df

,시도,시군구,마을이름,선정연도,체험,교육,숙박,음식,체험1등급항목,교육1등급항목,숙박가족형등급항목,으뜸촌
0,강원,정선,365행복마을,2021,2,,1,2,NaN,NaN,가족형,N
1,강원,양양,38평화마을,2019,1,,1,,"만들기,문화,건강",NaN,가족형,N
2,강원,삼척,가온밸리(가곡온천휴양마을),2020,1,2,,,NaN,NaN,NaN,N
3,강원,춘천,강언덕부엉이마을,2020,2,,1,2,NaN,NaN,"가족형,단체형",N
4,강원,횡성,개나리마을,2019,2,,2,,NaN,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...
796,충북,옥천,햇다래마을,2020,2,,1,,NaN,NaN,"가족형,단체형",N
797,충북,옥천,향수뜰마을,2019,2,2,3,3,NaN,NaN,NaN,N
798,충북,영동,황금을따는마을,2021,3,,3,,NaN,NaN,NaN,N
799,충북,영동,흙진주포도체험마을,2019,,,2,,NaN,NaN,NaN,N
800,충북,단양,흰여울마을,2020,1,,,1,"농사,만들기",NaN,NaN,N

In [84]:
df['지역'] = df['시도'] + ' ' + df['시군구']

In [85]:
df

,시도,시군구,마을이름,선정연도,체험,교육,숙박,음식,체험1등급항목,교육1등급항목,숙박가족형등급항목,으뜸촌,지역
0,강원,정선,365행복마을,2021,2,,1,2,NaN,NaN,가족형,N,강원 정선
1,강원,양양,38평화마을,2019,1,,1,,"만들기,문화,건강",NaN,가족형,N,강원 양양
2,강원,삼척,가온밸리(가곡온천휴양마을),2020,1,2,,,NaN,NaN,NaN,N,강원 삼척
3,강원,춘천,강언덕부엉이마을,2020,2,,1,2,NaN,NaN,"가족형,단체형",N,강원 춘천
4,강원,횡성,개나리마을,2019,2,,2,,NaN,NaN,NaN,N,강원 횡성
...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,충북,옥천,햇다래마을,2020,2,,1,,NaN,NaN,"가족형,단체형",N,충북 옥천
797,충북,옥천,향수뜰마을,2019,2,2,3,3,NaN,NaN,NaN,N,충북 옥천
798,충북,영동,황금을따는마을,2021,3,,3,,NaN,NaN,NaN,N,충북 영동
799,충북,영동,흙진주포도체험마을,2019,,,2,,NaN,NaN,NaN,N,충북 영동
800,충북,단양,흰여울마을,2020,1,,,1,"농사,만들기",NaN,NaN,N,충북 단양

#### 지역 이름 형식 맞추기

In [86]:
시군구코드 = '''11110 서울 종로구
11140 서울 중구
11170 서울 용산구
11200 서울 성동구
11215 서울 광진구
11230 서울 동대문구
11260 서울 중랑구
11290 서울 성북구
11305 서울 강북구
11320 서울 도봉구
11350 서울 노원구
11380 서울 은평구
11410 서울 서대문구
11440 서울 마포구
11470 서울 양천구
11500 서울 강서구
11530 서울 구로구
11545 서울 금천구
11560 서울 영등포구
11590 서울 동작구
11620 서울 관악구
11650 서울 서초구
11680 서울 강남구
11710 서울 송파구
11740 서울 강동구
26110 부산 중구
26140 부산 서구
26170 부산 동구
26200 부산 영도구
26230 부산 부산진구
26260 부산 동래구
26290 부산 남구
26320 부산 북구
26350 부산 해운대구
26380 부산 사하구
26410 부산 금정구
26440 부산 강서구
26470 부산 연제구
26500 부산 수영구
26530 부산 사상구
26710 부산 기장군
27110 대구 중구
27140 대구 동구
27170 대구 서구
27200 대구 남구
27230 대구 북구
27260 대구 수성구
27290 대구 달서구
27710 대구 달성군
28110 인천 중구
28140 인천 동구
28177 인천 미추홀구
28185 인천 연수구
28200 인천 남동구
28237 인천 부평구
28245 인천 계양구
28260 인천 서구
28710 인천 강화군
28720 인천 옹진군
29110 광주 동구
29140 광주 서구
29155 광주 남구
29170 광주 북구
29200 광주 광산구
30110 대전 동구
30140 대전 중구
30170 대전 서구
30200 대전 유성구
30230 대전 대덕구
31110 울산 중구
31140 울산 남구
31170 울산 동구
31200 울산 북구
31710 울산 울주군
36110 세종 세종시
41111 경기 수원시
41113 경기 수원시
41115 경기 수원시
41117 경기 수원시
41131 경기 성남시
41133 경기 성남시
41135 경기 성남시
41150 경기 의정부시
41171 경기 안양시
41173 경기 안양시
41190 경기 부천시
41210 경기 광명시
41220 경기 평택시
41250 경기 동두천시
41271 경기 안산시
41273 경기 안산시
41281 경기 고양시
41285 경기 고양시
41287 경기 고양시
41290 경기 과천시
41310 경기 구리시
41360 경기 남양주시
41370 경기 오산시
41390 경기 시흥시
41410 경기 군포시
41430 경기 의왕시
41450 경기 하남시
41461 경기 용인시
41463 경기 용인시
41465 경기 용인시
41480 경기 파주시
41500 경기 이천시
41550 경기 안성시
41570 경기 김포시
41590 경기 화성시
41610 경기 광주시
41630 경기 양주시
41650 경기 포천시
41670 경기 여주시
41730 경기 여주시
41800 경기 연천군
41820 경기 가평군
41830 경기 양평군
42110 강원 춘천시
42130 강원 원주시
42150 강원 강릉시
42170 강원 동해시
42190 강원 태백시
42210 강원 속초시
42230 강원 삼척시
42720 강원 홍천군
42730 강원 횡성군
42750 강원 영월군
42760 강원 평창군
42770 강원 정선군
42780 강원 철원군
42790 강원 화천군
42800 강원 양구군
42810 강원 인제군
42820 강원 고성군
42830 강원 양양군
43111 충북 청주시
43112 충북 청주시
43113 충북 청주시
43114 충북 청주시
43130 충북 충주시
43150 충북 제천시
43710 충북 청주시
43720 충북 보은군
43730 충북 옥천군
43740 충북 영동군
43745 충북 증평군
43750 충북 진천군
43760 충북 괴산군
43770 충북 음성군
43800 충북 단양군
44130 충남 천안시
44131 충남 천안시
44133 충남 천안시
44150 충남 공주시
44180 충남 보령시
44200 충남 아산시
44210 충남 서산시
44230 충남 논산시
44250 충남 계룡시
44270 충남 당진시
44710 충남 금산군
44730 충남 연기군
44760 충남 부여군
44770 충남 서천군
44790 충남 청양군
44800 충남 홍성군
44810 충남 예산군
44825 충남 태안군
45111 전북 전주시
45113 전북 전주시
45130 전북 군산시
45140 전북 익산시
45180 전북 정읍시
45190 전북 남원시
45210 전북 김제시
45710 전북 완주군
45720 전북 진안군
45730 전북 무주군
45740 전북 장수군
45750 전북 임실군
45770 전북 순창군
45790 전북 고창군
45800 전북 부안군
46110 전남 목포시
46130 전남 여수시
46150 전남 순천시
46170 전남 나주시
46230 전남 광양시
46710 전남 담양군
46720 전남 곡성군
46730 전남 구례군
46770 전남 고흥군
46780 전남 보성군
46790 전남 화순군
46800 전남 장흥군
46810 전남 강진군
46820 전남 해남군
46830 전남 영암군
46840 전남 무안군
46860 전남 함평군
46870 전남 영광군
46880 전남 장성군
46890 전남 완도군
46900 전남 진도군
46910 전남 신안군
47111 경북 포항시
47113 경북 포항시
47130 경북 경주시
47150 경북 김천시
47170 경북 안동시
47190 경북 구미시
47210 경북 영주시
47230 경북 영천시
47250 경북 상주시
47280 경북 문경시
47290 경북 경산시
47720 경북 군위군
47730 경북 의성군
47750 경북 청송군
47760 경북 영양군
47770 경북 영덕군
47820 경북 청도군
47830 경북 고령군
47840 경북 성주군
47850 경북 칠곡군
47900 경북 예천군
47920 경북 봉화군
47930 경북 울진군
47940 경북 울릉군
48121 경남 창원시
48123 경남 창원시
48125 경남 창원시
48127 경남 창원시
48129 경남 창원시
48170 경남 진주시
48220 경남 통영시
48240 경남 사천시
48250 경남 김해시
48270 경남 밀양시
48310 경남 거제시
48330 경남 양산시
48720 경남 의령군
48730 경남 함안군
48740 경남 창녕군
48820 경남 고성군
48840 경남 남해군
48850 경남 하동군
48860 경남 산청군
48870 경남 함양군
48880 경남 거창군
48890 경남 합천군
50110 제주 제주시
50130 제주 서귀포시'''.split('\n')

In [87]:
시군구_list = []
for i in 시군구코드:
  시군구_list.append(i[6:])

In [88]:
def 지역명_변환(data):
  for i in 시군구_list:
    if i.startswith(data):
      return i

In [89]:
df['시군구_변환'] = df['지역'].apply(지역명_변환).values

In [90]:
df[df['시군구_변환'].isnull()]

,시도,시군구,마을이름,선정연도,체험,교육,숙박,음식,체험1등급항목,교육1등급항목,숙박가족형등급항목,으뜸촌,지역,시군구_변환
340,경북,울주,못안마을,2020,3,,3,,NaN,NaN,NaN,N,경북 울주,None
417,세종,전동,청솔마을,2019,2,,2,,NaN,NaN,NaN,N,세종 전동,None

In [ ]:
df.loc[417, '시군구_변환'] = '세종 세종시'

In [ ]:
df[df['시도'] == '세종']

,시도,시군구,마을이름,선정연도,체험,교육,숙박,음식,체험1등급항목,교육1등급항목,숙박가족형등급항목,으뜸촌,지역,시군구_변환
416,세종,세종,아람달마을,2020,1,2,2,,NaN,NaN,NaN,N,세종 세종,세종 세종시
417,세종,전동,청솔마을,2019,2,,2,,NaN,NaN,NaN,N,세종 전동,세종 세종시

In [ ]:
df.to_pickle('/content/gdrive/MyDrive/문화관광 빅데이터 공모전/전처리/농촌지역rawdata.pkl')

#### 농촌관광지 데이터프레임 만들기

In [106]:
df = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/전처리/농촌지역rawdata.pkl')
df

,시도,시군구,마을이름,선정연도,체험,교육,숙박,음식,체험1등급항목,교육1등급항목,숙박가족형등급항목,으뜸촌,지역,시군구_변환
0,강원,정선,365행복마을,2021,2,,1,2,NaN,NaN,가족형,N,강원 정선,강원 정선군
1,강원,양양,38평화마을,2019,1,,1,,"만들기,문화,건강",NaN,가족형,N,강원 양양,강원 양양군
2,강원,삼척,가온밸리(가곡온천휴양마을),2020,1,2,,,NaN,NaN,NaN,N,강원 삼척,강원 삼척시
3,강원,춘천,강언덕부엉이마을,2020,2,,1,2,NaN,NaN,"가족형,단체형",N,강원 춘천,강원 춘천시
4,강원,횡성,개나리마을,2019,2,,2,,NaN,NaN,NaN,N,강원 횡성,강원 횡성군
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,충북,옥천,햇다래마을,2020,2,,1,,NaN,NaN,"가족형,단체형",N,충북 옥천,충북 옥천군
797,충북,옥천,향수뜰마을,2019,2,2,3,3,NaN,NaN,NaN,N,충북 옥천,충북 옥천군
798,충북,영동,황금을따는마을,2021,3,,3,,NaN,NaN,NaN,N,충북 영동,충북 영동군
799,충북,영동,흙진주포도체험마을,2019,,,2,,NaN,NaN,NaN,N,충북 영동,충북 영동군
800,충북,단양,흰여울마을,2020,1,,,1,"농사,만들기",NaN,NaN,N,충북 단양,충북 단양군

In [107]:
import numpy as np

In [108]:
for col in ['체험','교육', '숙박', '음식']:
  print(col, df[col].unique())

체험 ['2' '1' '  ' '3']
교육 ['  ' '2' '1' '3']
숙박 ['1' '  ' '2' '3']
음식 ['2' '  ' '1' '3']

In [109]:
# 결측치 NA 값 넣기
for col in ['체험','교육', '숙박', '음식']:
  for idx in range(len(df.index)):
    if df[col][idx] == '1':
      df[col][idx] = 1
    elif df[col][idx] == '2' :
      df[col][idx] = 2
    elif df[col][idx] == '3':
      df[col][idx] = 3
    elif df[col][idx] == '  ' :
      df[col][idx] = np.nan

<ipython-input-109-99cd3aeeb690>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col][idx] = 2
<ipython-input-109-99cd3aeeb690>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col][idx] = 1
<ipython-input-109-99cd3aeeb690>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col][idx] = np.nan
<ipython-input-109-99cd3aeeb690>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col][idx] = 3

In [110]:
df[['체험','교육', '숙박', '음식']] # 잘 들어갔나 확인

      체험   교육   숙박   음식
0      2  NaN    1    2
1      1  NaN    1  NaN
2      1    2  NaN  NaN
3      2  NaN    1    2
4      2  NaN    2  NaN
..   ...  ...  ...  ...
796    2  NaN    1  NaN
797    2    2    3    3
798    3  NaN    3  NaN
799  NaN  NaN    2  NaN
800    1  NaN  NaN    1

[801 rows x 4 columns]

In [111]:
# 컬럼별 값을 더하고 na를 제외한 값의 개수로 나눠 평균을 구했음
def NaMean(x):
  return x.sum() / x.count()

In [112]:
df.groupby('시군구_변환')['체험','교육', '숙박', '음식'].agg(NaMean)

<ipython-input-112-e4b52493fe99>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby('시군구_변환')['체험','교육', '숙박', '음식'].agg(NaMean)
<ipython-input-111-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()
<ipython-input-111-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()
<ipython-input-111-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()
<ipython-input-111-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()

              체험        교육        숙박        음식
시군구_변환
강원 강릉시  1.416667  2.333333  1.500000  1.555556
강원 고성군  2.000000  3.000000  2.000000  2.000000
강원 동해시  2.000000  2.000000  1.000000       NaN
강원 삼척시  1.750000  2.000000  1.714286  2.000000
강원 속초시  2.000000       NaN       NaN       NaN
...          ...       ...       ...       ...
충북 제천시  1.714286  3.000000  1.833333  1.750000
충북 증평군  2.000000  2.000000  2.000000  1.666667
충북 진천군  1.500000       NaN  1.500000  2.000000
충북 청주시  2.250000  2.000000  2.600000  3.000000
충북 충주시  2.000000  2.000000  2.250000  2.500000

[143 rows x 4 columns]

In [136]:
dataframe2 = df.groupby('시군구_변환')['체험','교육', '숙박', '음식'].agg(NaMean)
dataframe2

<ipython-input-136-babbeac5856d>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  dataframe2 = df.groupby('시군구_변환')['체험','교육', '숙박', '음식'].agg(NaMean)
<ipython-input-111-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()
<ipython-input-111-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()
<ipython-input-111-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()
<ipython-input-111-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()

              체험        교육        숙박        음식
시군구_변환
강원 강릉시  1.416667  2.333333  1.500000  1.555556
강원 고성군  2.000000  3.000000  2.000000  2.000000
강원 동해시  2.000000  2.000000  1.000000       NaN
강원 삼척시  1.750000  2.000000  1.714286  2.000000
강원 속초시  2.000000       NaN       NaN       NaN
...          ...       ...       ...       ...
충북 제천시  1.714286  3.000000  1.833333  1.750000
충북 증평군  2.000000  2.000000  2.000000  1.666667
충북 진천군  1.500000       NaN  1.500000  2.000000
충북 청주시  2.250000  2.000000  2.600000  3.000000
충북 충주시  2.000000  2.000000  2.250000  2.500000

[143 rows x 4 columns]

In [137]:
dataframe2 = dataframe2.fillna(df.mean()).round(3)
dataframe2

<ipython-input-137-00c178b05e51>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataframe2 = dataframe2.fillna(df.mean()).round(3)

           체험     교육     숙박     음식
시군구_변환
강원 강릉시  1.417  2.333  1.500  1.556
강원 고성군  2.000  3.000  2.000  2.000
강원 동해시  2.000  2.000  1.000  1.824
강원 삼척시  1.750  2.000  1.714  2.000
강원 속초시  2.000  1.996  1.860  1.824
...       ...    ...    ...    ...
충북 제천시  1.714  3.000  1.833  1.750
충북 증평군  2.000  2.000  2.000  1.667
충북 진천군  1.500  1.996  1.500  2.000
충북 청주시  2.250  2.000  2.600  3.000
충북 충주시  2.000  2.000  2.250  2.500

[143 rows x 4 columns]

In [114]:
df.groupby('시군구_변환')[['마을이름']].count() # 지역별 농촌마을 수

        마을이름
시군구_변환
강원 강릉시    12
강원 고성군     2
강원 동해시     2
강원 삼척시     9
강원 속초시     1
...      ...
충북 제천시     7
충북 증평군     4
충북 진천군     2
충북 청주시     5
충북 충주시     6

[143 rows x 1 columns]

In [115]:
#df[df['으뜸촌']!= 'N']
df['으뜸촌'] = df['으뜸촌'].apply(lambda x: 1 if x == 'Y' else 0).astype('int')

In [116]:
# 지역별 으뜸촌 개수
으뜸촌 = df.groupby('시군구_변환')[['으뜸촌']].sum()

In [117]:
dataframe = df.groupby('시군구_변환')[['마을이름']].count()
dataframe

        마을이름
시군구_변환
강원 강릉시    12
강원 고성군     2
강원 동해시     2
강원 삼척시     9
강원 속초시     1
...      ...
충북 제천시     7
충북 증평군     4
충북 진천군     2
충북 청주시     5
충북 충주시     6

[143 rows x 1 columns]

In [138]:
농촌관광지_df = pd.DataFrame()
농촌관광지_df['관광지역_시군구'] = dataframe.index.tolist()
농촌관광지_df['농촌마을_수'] = dataframe['마을이름'].values.tolist()
농촌관광지_df['농촌마을_체험_평균등급'] = dataframe2['체험'].values.tolist()
농촌관광지_df['농촌마을_교육_평균등급'] = dataframe2['교육'].values.tolist()
농촌관광지_df['농촌마을_숙박_평균등급'] = dataframe2['숙박'].values.tolist()
농촌관광지_df['농촌마을_음식_평균등급'] = dataframe2['음식'].values.tolist()
농촌관광지_df['농촌마을_으뜸촌_선정수'] = 으뜸촌['으뜸촌'].values.tolist()

In [139]:
농촌관광지_df

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0
...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0

In [177]:
농촌관광지_df.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/농촌관광지df생성.pkl')

In [157]:
df = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/농촌관광지df생성.pkl')
df

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0
...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0

#### 카드데이터 연결

In [152]:
c_data = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/전처리/card_travel.pkl')
c_data

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,강원,강원,강원 양양군,여행,교통,M,40,2021-07-01,RED,활동,18730606,78
1,인천,강원,강원 양양군,여행,관광쇼핑,F,50,2021-07-01,RED,활동,319575,26
2,충북,충북,충북 청주시,여행,관광쇼핑,F,40,2021-07-01,WHITE,활동,100688,17
3,충북,충북,충북 음성군,여행,체험,M,30,2021-07-01,RED,활동,1479676,35
4,인천,충남,충남 천안시,여행,체험,F,20,2021-07-01,WHITE,활동,700438,26
...,...,...,...,...,...,...,...,...,...,...,...,...
4681793,서울,강원,강원 고성군,여행,관광쇼핑,F,20,2022-06-01,RED,활동,672178,49
4681794,부산,충북,충북 제천시,여행,관광쇼핑,M,60,2022-06-01,WHITE,활동,79021,9
4681795,서울,충남,충남 천안시,여행,관광쇼핑,M,50,2022-06-01,RED,활동,158043,9
4681796,대구,충남,충남 천안시,여행,숙박,F,30,2022-06-01,WHITE,활동,493885,9
4681797,서울,충남,충남 아산시,여행,숙박,M,30,2022-06-01,RED,취침,3160868,9

In [153]:
# 농촌관광지역만 추출
시군구_농촌 = df['관광지역_시군구'].values.tolist()
c_data_농촌 = c_data[c_data['가맹점시군구'].isin(시군구_농촌)]

In [154]:
c_data_농촌

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,강원,강원,강원 양양군,여행,교통,M,40,2021-07-01,RED,활동,18730606,78
1,인천,강원,강원 양양군,여행,관광쇼핑,F,50,2021-07-01,RED,활동,319575,26
2,충북,충북,충북 청주시,여행,관광쇼핑,F,40,2021-07-01,WHITE,활동,100688,17
3,충북,충북,충북 음성군,여행,체험,M,30,2021-07-01,RED,활동,1479676,35
4,인천,충남,충남 천안시,여행,체험,F,20,2021-07-01,WHITE,활동,700438,26
...,...,...,...,...,...,...,...,...,...,...,...,...
4681793,서울,강원,강원 고성군,여행,관광쇼핑,F,20,2022-06-01,RED,활동,672178,49
4681794,부산,충북,충북 제천시,여행,관광쇼핑,M,60,2022-06-01,WHITE,활동,79021,9
4681795,서울,충남,충남 천안시,여행,관광쇼핑,M,50,2022-06-01,RED,활동,158043,9
4681796,대구,충남,충남 천안시,여행,숙박,F,30,2022-06-01,WHITE,활동,493885,9
4681797,서울,충남,충남 아산시,여행,숙박,M,30,2022-06-01,RED,취침,3160868,9

In [ ]:
# EDA 새로 해보기

In [ ]:
c_data_농촌.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2684497 entries, 0 to 4681797
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   자택광역시도          object
 1   가맹점광역시도         object
 2   가맹점시군구          object
 3   GB3             object
 4   GB2             object
 5   SEX_CCD         object
 6   CLN_AGE_R       int64
 7   TA_YM           datetime64[ns]
 8   DAW_CCD_R       object
 9   APV_TS_DL_TM_R  object
 10  VLM             int64
 11  USEC            int64
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 266.3+ MB

In [155]:
지역별_연령대별_이용 = c_data_농촌.groupby(['가맹점시군구','CLN_AGE_R'])['VLM','USEC'].sum()
지역별_연령대별_이용

<ipython-input-155-b8cb7654f7f5>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  지역별_연령대별_이용 = c_data_농촌.groupby(['가맹점시군구','CLN_AGE_R'])['VLM','USEC'].sum()

                           VLM     USEC
가맹점시군구 CLN_AGE_R
강원 강릉시 20          54297022158  1147478
       30         108399436143  1567237
       40         111561602803  1434881
       50          81348007762   990532
       60          46963174673   552024
...                        ...      ...
충북 충주시 20           7851096784   209753
       30          17024271175   494091
       40          21895055297   503371
       50          21938949374   402461
       60          15169601751   293413

[710 rows x 2 columns]

In [156]:
# 카드 이용건수 합계 _ 연령대별로 (다음에 기간이 맞는지 한번 전체적으로 확인해야 함)
지역별_연령대별_이용 = 지역별_연령대별_이용.unstack()
지역별_연령대별_이용

                   VLM                                                        \
CLN_AGE_R           20            30            40           50           60
가맹점시군구
강원 강릉시     54297022158  108399436143  111561602803  81348007762  46963174673
강원 고성군     10624957786   56008238103   82528619129  50404208475  39525400164
강원 동해시      4213380348   10796647185   13664087410  13308755399   8069285608
강원 삼척시      8894076116   45860241095   63491875068  36015519366  22264007540
강원 속초시     20850516075   70456266324   91564998073  62440965428  41451376382
...                ...           ...           ...          ...          ...
충북 제천시     12977593911   42543456529   42076595829  25405458123  17532548498
충북 증평군      1687909286    6330885768    9641625022  11533252592   6449149935
충북 진천군      2032573517    3430469506    5439783693   5278824557   2448733681
충북 청주시     35803154999   42023809159   46895586430  40094357684  19818229436
충북 충주시      7851096784   17024271175   21895055297  21938949374  15169601751

              USEC
CLN_AGE_R       20       30       40      50      60
가맹점시군구
강원 강릉시     1147478  1567237  1434881  990532  552024
강원 고성군      236627  1009571  1255043  664773  505690
강원 동해시       91003   163857   260025  205250  134194
강원 삼척시      143917   601522   747283  383051  241549
강원 속초시      481591  1122668  1345131  962638  618593
...            ...      ...      ...     ...     ...
충북 제천시      264708   753039   655702  373022  252826
충북 증평군       56600   320735   256707  115898   69334
충북 진천군       42046    75275   100083   87132   37515
충북 청주시      796993   826937   812536  651122  378616
충북 충주시      209753   494091   503371  402461  293413

[142 rows x 10 columns]

In [158]:
#지역별_연령대별_이용['USEC']
df2 = pd.merge(df, 지역별_연령대별_이용['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')
df2

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,20,30,40,50,60
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1147478.0,1567237.0,1434881.0,990532.0,552024.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,236627.0,1009571.0,1255043.0,664773.0,505690.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,91003.0,163857.0,260025.0,205250.0,134194.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,143917.0,601522.0,747283.0,383051.0,241549.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,481591.0,1122668.0,1345131.0,962638.0,618593.0
...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,264708.0,753039.0,655702.0,373022.0,252826.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,56600.0,320735.0,256707.0,115898.0,69334.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,42046.0,75275.0,100083.0,87132.0,37515.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,796993.0,826937.0,812536.0,651122.0,378616.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,209753.0,494091.0,503371.0,402461.0,293413.0

In [159]:
df2.rename(columns={20:'카드_20대_이용건수',30:'카드_30대_이용건수', 40:'카드_40대_이용건수', 50:'카드_50대_이용건수', 60:'카드_60대_이용건수'}, inplace=True)

In [160]:
df2

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_20대_이용건수,카드_30대_이용건수,카드_40대_이용건수,카드_50대_이용건수,카드_60대_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1147478.0,1567237.0,1434881.0,990532.0,552024.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,236627.0,1009571.0,1255043.0,664773.0,505690.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,91003.0,163857.0,260025.0,205250.0,134194.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,143917.0,601522.0,747283.0,383051.0,241549.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,481591.0,1122668.0,1345131.0,962638.0,618593.0
...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,264708.0,753039.0,655702.0,373022.0,252826.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,56600.0,320735.0,256707.0,115898.0,69334.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,42046.0,75275.0,100083.0,87132.0,37515.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,796993.0,826937.0,812536.0,651122.0,378616.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,209753.0,494091.0,503371.0,402461.0,293413.0

In [161]:
지역별_업종소분류별_이용 = c_data_농촌.groupby(['가맹점시군구','GB2'])['VLM','USEC'].sum()
지역별_업종소분류별_이용

<ipython-input-161-57608e68ce4e>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  지역별_업종소분류별_이용 = c_data_농촌.groupby(['가맹점시군구','GB2'])['VLM','USEC'].sum()

                      VLM     USEC
가맹점시군구 GB2
강원 강릉시 관광쇼핑    9406256968   512410
       교통      4640318354    35587
       숙박    363628144606  4307834
       여행사      637593609      988
       체험     24256930002   835333
...                   ...      ...
충북 충주시 관광쇼핑    1560131290    18099
       교통      1802504357     7699
       숙박     61257412340  1143215
       여행사      278244541      246
       체험     18980681853   733830

[654 rows x 2 columns]

In [162]:
지역별_업종소분류별_이용 = 지역별_업종소분류별_이용.unstack()

In [163]:
# 카드 이용건수 _ GB2별로 (업종 소분류)
df3 = pd.merge(df2, 지역별_업종소분류별_이용['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')
df3

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_20대_이용건수,카드_30대_이용건수,카드_40대_이용건수,카드_50대_이용건수,카드_60대_이용건수,관광쇼핑,교통,숙박,여행사,체험
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1147478.0,1567237.0,1434881.0,990532.0,552024.0,512410.0,35587.0,4307834.0,988.0,835333.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,236627.0,1009571.0,1255043.0,664773.0,505690.0,86367.0,209.0,3076538.0,501002.0,7588.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,91003.0,163857.0,260025.0,205250.0,134194.0,23638.0,32077.0,782379.0,910.0,15325.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,143917.0,601522.0,747283.0,383051.0,241549.0,68602.0,3420.0,1996406.0,17536.0,31358.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,481591.0,1122668.0,1345131.0,962638.0,618593.0,121180.0,983893.0,2640282.0,25579.0,759687.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,264708.0,753039.0,655702.0,373022.0,252826.0,44337.0,2556.0,654268.0,180.0,1597956.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,56600.0,320735.0,256707.0,115898.0,69334.0,1660.0,3503.0,101510.0,30.0,712571.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,42046.0,75275.0,100083.0,87132.0,37515.0,1799.0,963.0,326770.0,NaN,12519.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,796993.0,826937.0,812536.0,651122.0,378616.0,127574.0,37415.0,2774910.0,2955.0,523350.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,209753.0,494091.0,503371.0,402461.0,293413.0,18099.0,7699.0,1143215.0,246.0,733830.0

In [164]:
df3.rename(columns={'관광쇼핑':'카드_관광쇼핑_이용건수','교통':'카드_교통_이용건수', '숙박':'카드_숙박_이용건수', '여행사':'카드_여행사_이용건수', '체험':'카드_체험_이용건수'}, inplace=True)

In [165]:
df3

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_20대_이용건수,카드_30대_이용건수,카드_40대_이용건수,카드_50대_이용건수,카드_60대_이용건수,카드_관광쇼핑_이용건수,카드_교통_이용건수,카드_숙박_이용건수,카드_여행사_이용건수,카드_체험_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1147478.0,1567237.0,1434881.0,990532.0,552024.0,512410.0,35587.0,4307834.0,988.0,835333.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,236627.0,1009571.0,1255043.0,664773.0,505690.0,86367.0,209.0,3076538.0,501002.0,7588.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,91003.0,163857.0,260025.0,205250.0,134194.0,23638.0,32077.0,782379.0,910.0,15325.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,143917.0,601522.0,747283.0,383051.0,241549.0,68602.0,3420.0,1996406.0,17536.0,31358.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,481591.0,1122668.0,1345131.0,962638.0,618593.0,121180.0,983893.0,2640282.0,25579.0,759687.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,264708.0,753039.0,655702.0,373022.0,252826.0,44337.0,2556.0,654268.0,180.0,1597956.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,56600.0,320735.0,256707.0,115898.0,69334.0,1660.0,3503.0,101510.0,30.0,712571.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,42046.0,75275.0,100083.0,87132.0,37515.0,1799.0,963.0,326770.0,NaN,12519.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,796993.0,826937.0,812536.0,651122.0,378616.0,127574.0,37415.0,2774910.0,2955.0,523350.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,209753.0,494091.0,503371.0,402461.0,293413.0,18099.0,7699.0,1143215.0,246.0,733830.0

In [166]:
# 주중 / 주말 별 이용건수 (Red: 주말, White: 평일)
지역별_요일별_이용 = c_data_농촌.groupby(['가맹점시군구','DAW_CCD_R'])['VLM','USEC'].sum()
지역별_요일별_이용

<ipython-input-166-4e4ce05cc0b0>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  지역별_요일별_이용 = c_data_농촌.groupby(['가맹점시군구','DAW_CCD_R'])['VLM','USEC'].sum()

                           VLM     USEC
가맹점시군구 DAW_CCD_R
강원 강릉시 RED        161587011335  2415046
       WHITE      240982232204  3277106
강원 고성군 RED        103100931309  1588277
       WHITE      135990492348  2083427
강원 동해시 RED         16256170768   328989
...                        ...      ...
충북 진천군 WHITE       13356338487   223771
충북 청주시 RED         63498935711  1376495
       WHITE      121136201997  2089709
충북 충주시 RED         37960031960   981141
       WHITE       45918942421   921948

[284 rows x 2 columns]

In [167]:
지역별_요일별_이용 = 지역별_요일별_이용.unstack()

In [168]:
지역별_요일별_이용

                    VLM                   USEC
DAW_CCD_R           RED         WHITE      RED    WHITE
가맹점시군구
강원 강릉시     161587011335  240982232204  2415046  3277106
강원 고성군     103100931309  135990492348  1588277  2083427
강원 동해시      16256170768   33795985182   328989   525340
강원 삼척시      69377314431  107148404754   774949  1342373
강원 속초시     114042894203  172721228079  1871641  2658980
...                 ...           ...      ...      ...
충북 제천시      57638665626   82896987264   988239  1311058
충북 증평군      15044885393   20597937210   502978   316296
충북 진천군       5274046467   13356338487   118280   223771
충북 청주시      63498935711  121136201997  1376495  2089709
충북 충주시      37960031960   45918942421   981141   921948

[142 rows x 4 columns]

In [169]:
df4 = pd.merge(df3, 지역별_요일별_이용['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')
df4

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_20대_이용건수,카드_30대_이용건수,카드_40대_이용건수,카드_50대_이용건수,카드_60대_이용건수,카드_관광쇼핑_이용건수,카드_교통_이용건수,카드_숙박_이용건수,카드_여행사_이용건수,카드_체험_이용건수,RED,WHITE
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1147478.0,1567237.0,1434881.0,990532.0,552024.0,512410.0,35587.0,4307834.0,988.0,835333.0,2415046.0,3277106.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,236627.0,1009571.0,1255043.0,664773.0,505690.0,86367.0,209.0,3076538.0,501002.0,7588.0,1588277.0,2083427.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,91003.0,163857.0,260025.0,205250.0,134194.0,23638.0,32077.0,782379.0,910.0,15325.0,328989.0,525340.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,143917.0,601522.0,747283.0,383051.0,241549.0,68602.0,3420.0,1996406.0,17536.0,31358.0,774949.0,1342373.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,481591.0,1122668.0,1345131.0,962638.0,618593.0,121180.0,983893.0,2640282.0,25579.0,759687.0,1871641.0,2658980.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,264708.0,753039.0,655702.0,373022.0,252826.0,44337.0,2556.0,654268.0,180.0,1597956.0,988239.0,1311058.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,56600.0,320735.0,256707.0,115898.0,69334.0,1660.0,3503.0,101510.0,30.0,712571.0,502978.0,316296.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,42046.0,75275.0,100083.0,87132.0,37515.0,1799.0,963.0,326770.0,NaN,12519.0,118280.0,223771.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,796993.0,826937.0,812536.0,651122.0,378616.0,127574.0,37415.0,2774910.0,2955.0,523350.0,1376495.0,2089709.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,209753.0,494091.0,503371.0,402461.0,293413.0,18099.0,7699.0,1143215.0,246.0,733830.0,981141.0,921948.0

In [170]:
df4.rename(columns={'RED':'카드_주말_이용건수', 'WHITE':'카드_평일_이용건수'}, inplace=True)

In [171]:
df4

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_20대_이용건수,카드_30대_이용건수,카드_40대_이용건수,카드_50대_이용건수,카드_60대_이용건수,카드_관광쇼핑_이용건수,카드_교통_이용건수,카드_숙박_이용건수,카드_여행사_이용건수,카드_체험_이용건수,카드_주말_이용건수,카드_평일_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1147478.0,1567237.0,1434881.0,990532.0,552024.0,512410.0,35587.0,4307834.0,988.0,835333.0,2415046.0,3277106.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,236627.0,1009571.0,1255043.0,664773.0,505690.0,86367.0,209.0,3076538.0,501002.0,7588.0,1588277.0,2083427.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,91003.0,163857.0,260025.0,205250.0,134194.0,23638.0,32077.0,782379.0,910.0,15325.0,328989.0,525340.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,143917.0,601522.0,747283.0,383051.0,241549.0,68602.0,3420.0,1996406.0,17536.0,31358.0,774949.0,1342373.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,481591.0,1122668.0,1345131.0,962638.0,618593.0,121180.0,983893.0,2640282.0,25579.0,759687.0,1871641.0,2658980.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,264708.0,753039.0,655702.0,373022.0,252826.0,44337.0,2556.0,654268.0,180.0,1597956.0,988239.0,1311058.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,56600.0,320735.0,256707.0,115898.0,69334.0,1660.0,3503.0,101510.0,30.0,712571.0,502978.0,316296.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,42046.0,75275.0,100083.0,87132.0,37515.0,1799.0,963.0,326770.0,NaN,12519.0,118280.0,223771.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,796993.0,826937.0,812536.0,651122.0,378616.0,127574.0,37415.0,2774910.0,2955.0,523350.0,1376495.0,2089709.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,209753.0,494091.0,503371.0,402461.0,293413.0,18099.0,7699.0,1143215.0,246.0,733830.0,981141.0,921948.0

In [176]:
df4.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/농촌관광지df2번째.pkl')

저장