In [1]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
plt.rc('font', family='NanumBarunGothic')

#### 농촌지역_데이터 불러오기

In [6]:
base_df = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/농촌관광지df생성.pkl')
base_df

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0
...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0

#### 신한카드_데이터 불러오기

In [7]:
card_df = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/전처리/card_travel.pkl')
card_df

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,강원,강원,강원 양양군,여행,교통,M,40,2021-07-01,RED,활동,18730606,78
1,인천,강원,강원 양양군,여행,관광쇼핑,F,50,2021-07-01,RED,활동,319575,26
2,충북,충북,충북 청주시,여행,관광쇼핑,F,40,2021-07-01,WHITE,활동,100688,17
3,충북,충북,충북 음성군,여행,체험,M,30,2021-07-01,RED,활동,1479676,35
4,인천,충남,충남 천안시,여행,체험,F,20,2021-07-01,WHITE,활동,700438,26
...,...,...,...,...,...,...,...,...,...,...,...,...
4681793,서울,강원,강원 고성군,여행,관광쇼핑,F,20,2022-06-01,RED,활동,672178,49
4681794,부산,충북,충북 제천시,여행,관광쇼핑,M,60,2022-06-01,WHITE,활동,79021,9
4681795,서울,충남,충남 천안시,여행,관광쇼핑,M,50,2022-06-01,RED,활동,158043,9
4681796,대구,충남,충남 천안시,여행,숙박,F,30,2022-06-01,WHITE,활동,493885,9
4681797,서울,충남,충남 아산시,여행,숙박,M,30,2022-06-01,RED,취침,3160868,9

##### 2022년 데이터 추출

In [8]:
card_df['TA_YM'].dt.year.value_counts()

2022    1698133
2021    1528417
2020     752860
2023     702388
Name: TA_YM, dtype: int64

In [9]:
# 카드 데이터 2022년만 사용하기 (4681798개 -> 1698133개)
card_df_2022 = card_df[card_df['TA_YM'].dt.year == 2022].reset_index(drop=True)
card_df_2022

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,서울,경북,경북 김천시,여행,체험,M,40,2022-07-01,RED,활동,76115,10
1,인천,경북,경북 안동시,여행,숙박,M,50,2022-07-01,WHITE,활동,3597716,50
2,충남,경북,경북 영천시,여행,숙박,M,50,2022-07-01,WHITE,활동,1522305,30
3,경북,경북,경북 울진군,여행,숙박,F,40,2022-07-01,WHITE,활동,4711029,294
4,서울,경남,경남 창원시,여행,체험,M,20,2022-07-01,RED,활동,15223,10
...,...,...,...,...,...,...,...,...,...,...,...,...
1698128,서울,강원,강원 고성군,여행,관광쇼핑,F,20,2022-06-01,RED,활동,672178,49
1698129,부산,충북,충북 제천시,여행,관광쇼핑,M,60,2022-06-01,WHITE,활동,79021,9
1698130,서울,충남,충남 천안시,여행,관광쇼핑,M,50,2022-06-01,RED,활동,158043,9
1698131,대구,충남,충남 천안시,여행,숙박,F,30,2022-06-01,WHITE,활동,493885,9
1698132,서울,충남,충남 아산시,여행,숙박,M,30,2022-06-01,RED,취침,3160868,9

In [11]:
card_df_2022.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/card_df_2022.pkl')

##### 농촌지역에 해당하는 카드 사용 데이터 추출

In [12]:
# 농촌관광지역만 추출 (1698133개 -> 969500개)
시군구_농촌 = base_df['관광지역_시군구'].values.tolist()
c_data_농촌 = card_df_2022[card_df_2022['가맹점시군구'].isin(시군구_농촌)]

In [13]:
c_data_농촌 = c_data_농촌.reset_index(drop=True)
c_data_농촌

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,서울,경북,경북 김천시,여행,체험,M,40,2022-07-01,RED,활동,76115,10
1,인천,경북,경북 안동시,여행,숙박,M,50,2022-07-01,WHITE,활동,3597716,50
2,충남,경북,경북 영천시,여행,숙박,M,50,2022-07-01,WHITE,활동,1522305,30
3,경북,경북,경북 울진군,여행,숙박,F,40,2022-07-01,WHITE,활동,4711029,294
4,서울,경남,경남 창원시,여행,체험,M,20,2022-07-01,RED,활동,15223,10
...,...,...,...,...,...,...,...,...,...,...,...,...
969495,서울,강원,강원 고성군,여행,관광쇼핑,F,20,2022-06-01,RED,활동,672178,49
969496,부산,충북,충북 제천시,여행,관광쇼핑,M,60,2022-06-01,WHITE,활동,79021,9
969497,서울,충남,충남 천안시,여행,관광쇼핑,M,50,2022-06-01,RED,활동,158043,9
969498,대구,충남,충남 천안시,여행,숙박,F,30,2022-06-01,WHITE,활동,493885,9
969499,서울,충남,충남 아산시,여행,숙박,M,30,2022-06-01,RED,취침,3160868,9

#### 20대 데이터프레임 생성

In [14]:
df_age_20 = base_df.copy()

In [92]:
# 20대 해당하는 농촌지역_카드 데이터 추출
c_data_20 = c_data_농촌[c_data_농촌['CLN_AGE_R'] == 20].reset_index(drop=True)
c_data_20

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,서울,경남,경남 창원시,여행,체험,M,20,2022-07-01,RED,활동,15223,10
1,대구,경북,경북 영주시,여행,체험,F,20,2022-07-01,RED,활동,50743,10
2,대구,경남,경남 거제시,여행,숙박,M,20,2022-07-01,WHITE,활동,7851241,111
3,부산,경남,경남 하동군,여행,숙박,F,20,2022-08-01,RED,휴식,95006,9
4,경북,경북,경북 경산시,여행,체험,F,20,2022-05-01,WHITE,활동,1939020,12
...,...,...,...,...,...,...,...,...,...,...,...,...
157111,광주,전북,전북 남원시,여행,숙박,M,20,2022-06-01,WHITE,휴식,74082,9
157112,대구,경북,경북 칠곡군,여행,숙박,M,20,2022-06-01,WHITE,휴식,938382,19
157113,강원,경기,경기 김포시,여행,숙박,F,20,2022-06-01,WHITE,휴식,246942,9
157114,강원,강원,강원 철원군,여행,숙박,F,20,2022-06-01,WHITE,취침,493885,9
157115,서울,강원,강원 고성군,여행,관광쇼핑,F,20,2022-06-01,RED,활동,672178,49

In [93]:
c_data_20.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/2022_농촌지역_카드_20대.pkl')

##### 카드 총 이용금액 & 이용건수

In [17]:
c_data_20.groupby('가맹점시군구')[['VLM', 'USEC']].sum()

                VLM    USEC
가맹점시군구
강원 강릉시  18516074732  404279
강원 고성군   4580152132  100803
강원 동해시   1566478646   33655
강원 삼척시   3256333194   52380
강원 속초시   8113997185  207626
...             ...     ...
충북 제천시   5381104554  110959
충북 증평군    481433138   17794
충북 진천군    762943368   14981
충북 청주시  12246621929  263289
충북 충주시   2579826458   67459

[142 rows x 2 columns]

In [18]:
df_age_20 = pd.merge(df_age_20, c_data_20.groupby('가맹점시군구')[['VLM', 'USEC']].sum(), how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [19]:
df_age_20.rename(columns={'VLM':'카드_총_이용금액', 'USEC':'카드_총_이용건수'}, inplace=True)

In [20]:
df_age_20

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1.851607e+10,404279.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,4.580152e+09,100803.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,1.566479e+09,33655.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,3.256333e+09,52380.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,8.113997e+09,207626.0
...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,5.381105e+09,110959.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,4.814331e+08,17794.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,7.629434e+08,14981.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,1.224662e+10,263289.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,2.579826e+09,67459.0

##### 업종 소분류별_카드 이용건수

In [21]:
c_data_20.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()

           USEC
GB2        관광쇼핑       교통        숙박      여행사       체험
가맹점시군구
강원 강릉시  64693.0   2051.0  282069.0     46.0  55420.0
강원 고성군   2757.0      9.0   84623.0  13274.0    140.0
강원 동해시   1109.0   2014.0   30028.0     11.0    493.0
강원 삼척시    913.0    338.0   48535.0    519.0   2075.0
강원 속초시   9115.0  31244.0   81047.0    647.0  85573.0
...         ...      ...       ...      ...      ...
충북 제천시   2589.0     85.0   25301.0     20.0  82964.0
충북 증평군     20.0     50.0    5166.0      NaN  12558.0
충북 진천군     20.0     31.0   14808.0      NaN    122.0
충북 청주시   1017.0   2368.0  229123.0    168.0  30613.0
충북 충주시    100.0    876.0   42301.0      NaN  24182.0

[142 rows x 5 columns]

In [22]:
df_age_20 = pd.merge(df_age_20, c_data_20.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [23]:
df_age_20.rename(columns={'관광쇼핑':'카드_관광쇼핑_이용건수','교통':'카드_교통_이용건수', '숙박':'카드_숙박_이용건수', '여행사':'카드_여행사_이용건수', '체험':'카드_체험_이용건수'}, inplace=True)

##### 주중/주말 별 이용건수

In [24]:
# 주중 / 주말 별 이용건수 (Red: 주말, White: 평일)
c_data_20.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC']

DAW_CCD_R     RED   WHITE
가맹점시군구
강원 강릉시     175008  229271
강원 고성군      42498   58305
강원 동해시      12754   20901
강원 삼척시      19787   32593
강원 속초시      89948  117678
...           ...     ...
충북 제천시      47514   63445
충북 증평군      10383    7411
충북 진천군       5004    9977
충북 청주시     117301  145988
충북 충주시      34132   33327

[142 rows x 2 columns]

In [25]:
df_age_20 = pd.merge(df_age_20, c_data_20.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [26]:
df_age_20.rename(columns={'RED':'카드_주말_이용건수', 'WHITE':'카드_평일_이용건수'}, inplace=True)

In [28]:
df_age_20

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수,카드_관광쇼핑_이용건수,카드_교통_이용건수,카드_숙박_이용건수,카드_여행사_이용건수,카드_체험_이용건수,카드_주말_이용건수,카드_평일_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1.851607e+10,404279.0,64693.0,2051.0,282069.0,46.0,55420.0,175008.0,229271.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,4.580152e+09,100803.0,2757.0,9.0,84623.0,13274.0,140.0,42498.0,58305.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,1.566479e+09,33655.0,1109.0,2014.0,30028.0,11.0,493.0,12754.0,20901.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,3.256333e+09,52380.0,913.0,338.0,48535.0,519.0,2075.0,19787.0,32593.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,8.113997e+09,207626.0,9115.0,31244.0,81047.0,647.0,85573.0,89948.0,117678.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,5.381105e+09,110959.0,2589.0,85.0,25301.0,20.0,82964.0,47514.0,63445.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,4.814331e+08,17794.0,20.0,50.0,5166.0,NaN,12558.0,10383.0,7411.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,7.629434e+08,14981.0,20.0,31.0,14808.0,NaN,122.0,5004.0,9977.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,1.224662e+10,263289.0,1017.0,2368.0,229123.0,168.0,30613.0,117301.0,145988.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,2.579826e+09,67459.0,100.0,876.0,42301.0,NaN,24182.0,34132.0,33327.0

In [27]:
df_age_20.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/df_20대.pkl')

#### 30대 데이터프레임 생성

In [29]:
df_age_30 = base_df.copy()

In [30]:
# 30대 해당하는 농촌지역_카드 데이터 추출
c_data_30 = c_data_농촌[c_data_농촌['CLN_AGE_R'] == 30].reset_index(drop=True)
c_data_30

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,충북,경남,경남 창원시,여행,숙박,F,30,2022-07-01,WHITE,활동,558178,10
1,제주,제주,제주 서귀포시,여행,숙박,M,30,2022-07-01,WHITE,활동,401479660,3278
2,인천,경남,경남 남해군,여행,관광쇼핑,M,30,2022-08-01,WHITE,활동,864556,19
3,경남,경남,경남 산청군,여행,숙박,F,30,2022-08-01,RED,활동,4760761,38
4,서울,전남,전남 장성군,여행,숙박,M,30,2022-05-01,RED,활동,605943,12
...,...,...,...,...,...,...,...,...,...,...,...,...
212733,대전,경남,경남 사천시,여행,숙박,M,30,2022-06-01,RED,휴식,691439,9
212734,인천,제주,제주 서귀포시,여행,관광쇼핑,F,30,2022-06-01,RED,활동,16632191,464
212735,경기,강원,강원 동해시,여행,교통,M,30,2022-06-01,RED,활동,790217,9
212736,대구,충남,충남 천안시,여행,숙박,F,30,2022-06-01,WHITE,활동,493885,9
212737,서울,충남,충남 아산시,여행,숙박,M,30,2022-06-01,RED,취침,3160868,9

In [31]:
c_data_30.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/2022_농촌지역_카드_30대.pkl')

##### 카드 총 이용금액 & 이용건수

In [32]:
c_data_30.groupby('가맹점시군구')[['VLM', 'USEC']].sum()

                VLM    USEC
가맹점시군구
강원 강릉시  41456822210  601638
강원 고성군  25218427719  444318
강원 동해시   3058067046   68740
강원 삼척시  18044350843  239418
강원 속초시  27493957919  471273
...             ...     ...
충북 제천시  19029536221  342202
충북 증평군   1724236873  100533
충북 진천군   1421974332   29997
충북 청주시  15705185288  324898
충북 충주시   6855220976  201238

[142 rows x 2 columns]

In [33]:
df_age_30 = pd.merge(df_age_30, c_data_30.groupby('가맹점시군구')[['VLM', 'USEC']].sum(), how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [34]:
df_age_30.rename(columns={'VLM':'카드_총_이용금액', 'USEC':'카드_총_이용건수'}, inplace=True)

In [35]:
df_age_30

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,4.145682e+10,601638.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,2.521843e+10,444318.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,3.058067e+09,68740.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,1.804435e+10,239418.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,2.749396e+10,471273.0
...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,1.902954e+10,342202.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,1.724237e+09,100533.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,1.421974e+09,29997.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,1.570519e+10,324898.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,6.855221e+09,201238.0

##### 업종 소분류별_카드 이용건수

In [36]:
c_data_30.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()

           USEC
GB2        관광쇼핑       교통        숙박      여행사        체험
가맹점시군구
강원 강릉시  48366.0   2974.0  427237.0     41.0  123020.0
강원 고성군   6893.0     28.0  392011.0  44113.0    1273.0
강원 동해시   2171.0   3204.0   61996.0     79.0    1290.0
강원 삼척시   2536.0    190.0  230263.0   1705.0    4724.0
강원 속초시  12580.0  76854.0  230161.0   1328.0  150350.0
...         ...      ...       ...      ...       ...
충북 제천시   6939.0     62.0   38845.0      NaN  296356.0
충북 증평군     80.0    180.0    7073.0      NaN   93200.0
충북 진천군    267.0    117.0   27490.0      NaN    2123.0
충북 청주시   3588.0   3264.0  209395.0    291.0  108360.0
충북 충주시    403.0    420.0   69400.0      NaN  131015.0

[142 rows x 5 columns]

In [37]:
df_age_30 = pd.merge(df_age_30, c_data_30.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [38]:
df_age_30.rename(columns={'관광쇼핑':'카드_관광쇼핑_이용건수','교통':'카드_교통_이용건수', '숙박':'카드_숙박_이용건수', '여행사':'카드_여행사_이용건수', '체험':'카드_체험_이용건수'}, inplace=True)

##### 주중/주말 별 이용건수

In [39]:
# 주중 / 주말 별 이용건수 (Red: 주말, White: 평일)
c_data_30.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC']

DAW_CCD_R     RED   WHITE
가맹점시군구
강원 강릉시     276638  325000
강원 고성군     199437  244881
강원 동해시      28969   39771
강원 삼척시      90665  148753
강원 속초시     210549  260724
...           ...     ...
충북 제천시     150587  191615
충북 증평군      72077   28456
충북 진천군      12615   17382
충북 청주시     154878  170020
충북 충주시     122265   78973

[142 rows x 2 columns]

In [40]:
df_age_30 = pd.merge(df_age_30, c_data_30.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [41]:
df_age_30.rename(columns={'RED':'카드_주말_이용건수', 'WHITE':'카드_평일_이용건수'}, inplace=True)

In [43]:
df_age_30.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/df_30대.pkl')

#### 40대 데이터프레임 생성

In [44]:
df_age_40 = base_df.copy()

In [45]:
# 40대 해당하는 농촌지역_카드 데이터 추출
c_data_40 = c_data_농촌[c_data_농촌['CLN_AGE_R'] == 40].reset_index(drop=True)
c_data_40

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,서울,경북,경북 김천시,여행,체험,M,40,2022-07-01,RED,활동,76115,10
1,경북,경북,경북 울진군,여행,숙박,F,40,2022-07-01,WHITE,활동,4711029,294
2,서울,경남,경남 진주시,여행,숙박,M,40,2022-07-01,WHITE,활동,13173020,213
3,강원,경남,경남 통영시,여행,숙박,F,40,2022-07-01,WHITE,활동,2337246,81
4,충북,경남,경남 합천군,여행,숙박,M,40,2022-07-01,WHITE,활동,964127,20
...,...,...,...,...,...,...,...,...,...,...,...,...
228709,부산,경남,경남 남해군,여행,관광쇼핑,F,40,2022-06-01,RED,활동,888994,9
228710,경기,제주,제주 서귀포시,여행,숙박,M,40,2022-06-01,RED,취침,2494122,29
228711,강원,경기,경기 포천시,여행,체험,F,40,2022-06-01,RED,활동,454374,39
228712,강원,강원,강원 강릉시,여행,관광쇼핑,F,40,2022-06-01,WHITE,휴식,365475,9
228713,대구,강원,강원 철원군,여행,숙박,F,40,2022-06-01,RED,취침,197554,9

In [46]:
c_data_40.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/2022_농촌지역_카드_40대.pkl')

##### 카드 총 이용금액 & 이용건수

In [47]:
c_data_40.groupby('가맹점시군구')[['VLM', 'USEC']].sum()

                VLM    USEC
가맹점시군구
강원 강릉시  45131923684  587866
강원 고성군  38127019120  564869
강원 동해시   5519696574  107262
강원 삼척시  26470968613  309020
강원 속초시  36849344545  566878
...             ...     ...
충북 제천시  18482154413  291691
충북 증평군   2600341002   86590
충북 진천군   2191617610   39501
충북 청주시  18134037648  313779
충북 충주시   8688927177  205980

[142 rows x 2 columns]

In [48]:
df_age_40 = pd.merge(df_age_40, c_data_40.groupby('가맹점시군구')[['VLM', 'USEC']].sum(), how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [49]:
df_age_40.rename(columns={'VLM':'카드_총_이용금액', 'USEC':'카드_총_이용건수'}, inplace=True)

In [50]:
df_age_40

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,4.513192e+10,587866.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,3.812702e+10,564869.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,5.519697e+09,107262.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,2.647097e+10,309020.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,3.684934e+10,566878.0
...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,1.848215e+10,291691.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,2.600341e+09,86590.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,2.191618e+09,39501.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,1.813404e+10,313779.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,8.688927e+09,205980.0

##### 업종 소분류별_카드 이용건수

In [51]:
c_data_40.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()

           USEC
GB2        관광쇼핑        교통        숙박      여행사        체험
가맹점시군구
강원 강릉시  50533.0    3972.0  439412.0     78.0   93871.0
강원 고성군  10575.0      33.0  482049.0  69976.0    2236.0
강원 동해시   3001.0    4858.0   97460.0    103.0    1840.0
강원 삼척시   4320.0     351.0  297374.0   2179.0    4796.0
강원 속초시  11899.0  103144.0  302561.0   1742.0  147532.0
...         ...       ...       ...      ...       ...
충북 제천시   9589.0     137.0   52352.0      9.0  229604.0
충북 증평군    158.0     211.0    9528.0      NaN   76693.0
충북 진천군    356.0      75.0   37807.0      NaN    1263.0
충북 청주시   6172.0    3360.0  239470.0    240.0   64537.0
충북 충주시   1055.0     608.0  103072.0     22.0  101223.0

[142 rows x 5 columns]

In [52]:
df_age_40 = pd.merge(df_age_40, c_data_40.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [53]:
df_age_40.rename(columns={'관광쇼핑':'카드_관광쇼핑_이용건수','교통':'카드_교통_이용건수', '숙박':'카드_숙박_이용건수', '여행사':'카드_여행사_이용건수', '체험':'카드_체험_이용건수'}, inplace=True)

##### 주중/주말 별 이용건수

In [54]:
# 주중 / 주말 별 이용건수 (Red: 주말, White: 평일)
c_data_40.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC']

DAW_CCD_R     RED   WHITE
가맹점시군구
강원 강릉시     259298  328568
강원 고성군     259923  304946
강원 동해시      43807   63455
강원 삼척시     120807  188213
강원 속초시     258921  307957
...           ...     ...
충북 제천시     139573  152118
충북 증평군      58162   28428
충북 진천군      13605   25896
충북 청주시     123200  190579
충북 충주시     115886   90094

[142 rows x 2 columns]

In [55]:
df_age_40 = pd.merge(df_age_40, c_data_40.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [56]:
df_age_40.rename(columns={'RED':'카드_주말_이용건수', 'WHITE':'카드_평일_이용건수'}, inplace=True)

In [57]:
df_age_40

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수,카드_관광쇼핑_이용건수,카드_교통_이용건수,카드_숙박_이용건수,카드_여행사_이용건수,카드_체험_이용건수,카드_주말_이용건수,카드_평일_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,4.513192e+10,587866.0,50533.0,3972.0,439412.0,78.0,93871.0,259298.0,328568.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,3.812702e+10,564869.0,10575.0,33.0,482049.0,69976.0,2236.0,259923.0,304946.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,5.519697e+09,107262.0,3001.0,4858.0,97460.0,103.0,1840.0,43807.0,63455.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,2.647097e+10,309020.0,4320.0,351.0,297374.0,2179.0,4796.0,120807.0,188213.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,3.684934e+10,566878.0,11899.0,103144.0,302561.0,1742.0,147532.0,258921.0,307957.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,1.848215e+10,291691.0,9589.0,137.0,52352.0,9.0,229604.0,139573.0,152118.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,2.600341e+09,86590.0,158.0,211.0,9528.0,NaN,76693.0,58162.0,28428.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,2.191618e+09,39501.0,356.0,75.0,37807.0,NaN,1263.0,13605.0,25896.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,1.813404e+10,313779.0,6172.0,3360.0,239470.0,240.0,64537.0,123200.0,190579.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,8.688927e+09,205980.0,1055.0,608.0,103072.0,22.0,101223.0,115886.0,90094.0

In [59]:
df_age_40.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/df_40대.pkl')

#### 50대 데이터프레임 생성

In [60]:
df_age_50 = base_df.copy()

In [61]:
# 50대 해당하는 농촌지역_카드 데이터 추출
c_data_50 = c_data_농촌[c_data_농촌['CLN_AGE_R'] == 50].reset_index(drop=True)
c_data_50

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,인천,경북,경북 안동시,여행,숙박,M,50,2022-07-01,WHITE,활동,3597716,50
1,충남,경북,경북 영천시,여행,숙박,M,50,2022-07-01,WHITE,활동,1522305,30
2,광주,경남,경남 통영시,여행,숙박,F,50,2022-08-01,RED,활동,8703519,38
3,전북,제주,제주 서귀포시,여행,체험,M,50,2022-12-01,WHITE,활동,5708263,121
4,충북,경북,경북 포항시,여행,교통,M,50,2022-05-01,RED,활동,545349,12
...,...,...,...,...,...,...,...,...,...,...,...,...
211706,경남,전남,전남 장흥군,여행,숙박,M,50,2022-06-01,RED,휴식,345719,9
211707,부산,제주,제주 제주시,여행,체험,M,50,2022-06-01,WHITE,휴식,197554,9
211708,울산,경남,경남 거창군,여행,숙박,M,50,2022-06-01,WHITE,휴식,493885,9
211709,제주,강원,강원 정선군,여행,숙박,F,50,2022-06-01,WHITE,취침,731938,9
211710,서울,충남,충남 천안시,여행,관광쇼핑,M,50,2022-06-01,RED,활동,158043,9

In [62]:
c_data_50.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/2022_농촌지역_카드_50대.pkl')

##### 카드 총 이용금액 & 이용건수

In [63]:
c_data_50.groupby('가맹점시군구')[['VLM', 'USEC']].sum()

                VLM    USEC
가맹점시군구
강원 강릉시  32606144662  389836
강원 고성군  21958930207  280426
강원 동해시   5707775627   85459
강원 삼척시  14235791380  147462
강원 속초시  24846810794  391736
...             ...     ...
충북 제천시  10983759384  159514
충북 증평군   3209260965   34765
충북 진천군   2236908388   35815
충북 청주시  15487003778  247411
충북 충주시   8793208851  158568

[142 rows x 2 columns]

In [64]:
df_age_50 = pd.merge(df_age_50, c_data_50.groupby('가맹점시군구')[['VLM', 'USEC']].sum(), how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [65]:
df_age_50.rename(columns={'VLM':'카드_총_이용금액', 'USEC':'카드_총_이용건수'}, inplace=True)

In [66]:
df_age_50

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,3.260614e+10,389836.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,2.195893e+10,280426.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,5.707776e+09,85459.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,1.423579e+10,147462.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,2.484681e+10,391736.0
...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,1.098376e+10,159514.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,3.209261e+09,34765.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,2.236908e+09,35815.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,1.548700e+10,247411.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,8.793209e+09,158568.0

##### 업종 소분류별_카드 이용건수

In [67]:
c_data_50.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()

           USEC
GB2        관광쇼핑       교통        숙박      여행사        체험
가맹점시군구
강원 강릉시  30082.0   4698.0  315157.0    116.0   39783.0
강원 고성군   7927.0     40.0  224102.0  47837.0     520.0
강원 동해시   2164.0   5336.0   76782.0    118.0    1059.0
강원 삼척시   5852.0    147.0  137125.0   2288.0    2050.0
강원 속초시   8767.0  99260.0  220289.0    767.0   62653.0
...         ...      ...       ...      ...       ...
충북 제천시   4882.0    140.0   51810.0     52.0  102630.0
충북 증평군    310.0    434.0   10305.0      NaN   23716.0
충북 진천군    151.0     42.0   35379.0      NaN     243.0
충북 청주시   9726.0   2966.0  216428.0    386.0   17905.0
충북 충주시   2146.0    758.0  121253.0     32.0   34379.0

[142 rows x 5 columns]

In [68]:
df_age_50 = pd.merge(df_age_50, c_data_50.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [69]:
df_age_50.rename(columns={'관광쇼핑':'카드_관광쇼핑_이용건수','교통':'카드_교통_이용건수', '숙박':'카드_숙박_이용건수', '여행사':'카드_여행사_이용건수', '체험':'카드_체험_이용건수'}, inplace=True)

##### 주중/주말 별 이용건수

In [70]:
# 주중 / 주말 별 이용건수 (Red: 주말, White: 평일)
c_data_50.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC']

DAW_CCD_R     RED   WHITE
가맹점시군구
강원 강릉시     154123  235713
강원 고성군     116501  163925
강원 동해시      30595   54864
강원 삼척시      53319   94143
강원 속초시     155127  236609
...           ...     ...
충북 제천시      64145   95369
충북 증평군      12832   21933
충북 진천군      10708   25107
충북 청주시      82463  164948
충북 충주시      73257   85311

[142 rows x 2 columns]

In [71]:
df_age_50 = pd.merge(df_age_50, c_data_50.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [72]:
df_age_50.rename(columns={'RED':'카드_주말_이용건수', 'WHITE':'카드_평일_이용건수'}, inplace=True)

In [73]:
df_age_50

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수,카드_관광쇼핑_이용건수,카드_교통_이용건수,카드_숙박_이용건수,카드_여행사_이용건수,카드_체험_이용건수,카드_주말_이용건수,카드_평일_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,3.260614e+10,389836.0,30082.0,4698.0,315157.0,116.0,39783.0,154123.0,235713.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,2.195893e+10,280426.0,7927.0,40.0,224102.0,47837.0,520.0,116501.0,163925.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,5.707776e+09,85459.0,2164.0,5336.0,76782.0,118.0,1059.0,30595.0,54864.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,1.423579e+10,147462.0,5852.0,147.0,137125.0,2288.0,2050.0,53319.0,94143.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,2.484681e+10,391736.0,8767.0,99260.0,220289.0,767.0,62653.0,155127.0,236609.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,1.098376e+10,159514.0,4882.0,140.0,51810.0,52.0,102630.0,64145.0,95369.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,3.209261e+09,34765.0,310.0,434.0,10305.0,NaN,23716.0,12832.0,21933.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,2.236908e+09,35815.0,151.0,42.0,35379.0,NaN,243.0,10708.0,25107.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,1.548700e+10,247411.0,9726.0,2966.0,216428.0,386.0,17905.0,82463.0,164948.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,8.793209e+09,158568.0,2146.0,758.0,121253.0,32.0,34379.0,73257.0,85311.0

In [75]:
df_age_50.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/df_50대.pkl')

#### 60대 데이터프레임 생성

In [76]:
df_age_60 = base_df.copy()

In [77]:
# 60대 해당하는 농촌지역_카드 데이터 추출
c_data_60 = c_data_농촌[c_data_농촌['CLN_AGE_R'] == 60].reset_index(drop=True)
c_data_60

,자택광역시도,가맹점광역시도,가맹점시군구,GB3,GB2,SEX_CCD,CLN_AGE_R,TA_YM,DAW_CCD_R,APV_TS_DL_TM_R,VLM,USEC
0,경남,경남,경남 창원시,여행,체험,M,60,2022-07-01,WHITE,활동,507435,10
1,서울,제주,제주 제주시,여행,숙박,M,60,2022-07-01,RED,활동,82266384,436
2,충남,경남,경남 진주시,여행,숙박,M,60,2022-07-01,WHITE,휴식,8220451,30
3,대구,경남,경남 진주시,여행,숙박,M,60,2022-12-01,RED,휴식,441730,11
4,광주,강원,강원 고성군,여행,관광쇼핑,M,60,2022-07-01,WHITE,활동,329832,20
...,...,...,...,...,...,...,...,...,...,...,...,...
159216,대전,충남,충남 예산군,여행,체험,F,60,2022-06-01,RED,활동,1027282,19
159217,광주,전남,전남 담양군,여행,체험,F,60,2022-06-01,RED,활동,1113218,138
159218,경남,경남,경남 고성군,여행,체험,M,60,2022-06-01,WHITE,활동,2108891,158
159219,서울,제주,제주 제주시,여행,숙박,M,60,2022-06-01,RED,취침,3457199,49
159220,부산,충북,충북 제천시,여행,관광쇼핑,M,60,2022-06-01,WHITE,활동,79021,9

In [78]:
c_data_60.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/2022_농촌지역_카드_60대.pkl')

##### 카드 총 이용금액 & 이용건수

In [79]:
c_data_60.groupby('가맹점시군구')[['VLM', 'USEC']].sum()

                VLM    USEC
가맹점시군구
강원 강릉시  19804511890  224267
강원 고성군  17964740288  222954
강원 동해시   3487002514   57697
강원 삼척시   9269620656   94291
강원 속초시  16657456588  253596
...             ...     ...
충북 제천시   7523613635  112702
충북 증평군   2207701267   24262
충북 진천군    995621283   16319
충북 청주시   7753994107  148677
충북 충주시   6209599225  119172

[142 rows x 2 columns]

In [80]:
df_age_60 = pd.merge(df_age_60, c_data_60.groupby('가맹점시군구')[['VLM', 'USEC']].sum(), how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [81]:
df_age_60.rename(columns={'VLM':'카드_총_이용금액', 'USEC':'카드_총_이용건수'}, inplace=True)

In [82]:
df_age_60

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1.980451e+10,224267.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,1.796474e+10,222954.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,3.487003e+09,57697.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,9.269621e+09,94291.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,1.665746e+10,253596.0
...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,7.523614e+09,112702.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,2.207701e+09,24262.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,9.956213e+08,16319.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,7.753994e+09,148677.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,6.209599e+09,119172.0

##### 업종 소분류별_카드 이용건수

In [83]:
c_data_60.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()

           USEC
GB2        관광쇼핑       교통        숙박      여행사       체험
가맹점시군구
강원 강릉시  14697.0   4360.0  185992.0     59.0  19159.0
강원 고성군   7338.0     12.0  173540.0  41870.0    194.0
강원 동해시   1289.0   2895.0   52897.0     90.0    526.0
강원 삼척시   9103.0    271.0   80647.0   3234.0   1036.0
강원 속초시   6132.0  69282.0  145186.0    598.0  32398.0
...         ...      ...       ...      ...      ...
충북 제천시   4615.0     78.0   48779.0      9.0  59221.0
충북 증평군    237.0    324.0    5929.0      NaN  17772.0
충북 진천군    179.0     10.0   15872.0      NaN    258.0
충북 청주시  21861.0   1261.0  110585.0    394.0  14576.0
충북 충주시   2310.0    291.0   93014.0     28.0  23529.0

[142 rows x 5 columns]

In [84]:
df_age_60 = pd.merge(df_age_60, c_data_60.groupby(['가맹점시군구','GB2'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [85]:
df_age_60.rename(columns={'관광쇼핑':'카드_관광쇼핑_이용건수','교통':'카드_교통_이용건수', '숙박':'카드_숙박_이용건수', '여행사':'카드_여행사_이용건수', '체험':'카드_체험_이용건수'}, inplace=True)

##### 주중/주말 별 이용건수

In [86]:
# 주중 / 주말 별 이용건수 (Red: 주말, White: 평일)
c_data_60.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC']

DAW_CCD_R    RED   WHITE
가맹점시군구
강원 강릉시     76667  147600
강원 고성군     76115  146839
강원 동해시     18355   39342
강원 삼척시     26654   67637
강원 속초시     81787  171809
...          ...     ...
충북 제천시     39245   73457
충북 증평군      8244   16018
충북 진천군      4631   11688
충북 청주시     48286  100391
충북 충주시     51726   67446

[142 rows x 2 columns]

In [87]:
df_age_60 = pd.merge(df_age_60, c_data_60.groupby(['가맹점시군구','DAW_CCD_R'])[['USEC']].sum().unstack()['USEC'], how='left', left_on='관광지역_시군구', right_on='가맹점시군구')

In [88]:
df_age_60.rename(columns={'RED':'카드_주말_이용건수', 'WHITE':'카드_평일_이용건수'}, inplace=True)

In [89]:
df_age_60

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_총_이용금액,카드_총_이용건수,카드_관광쇼핑_이용건수,카드_교통_이용건수,카드_숙박_이용건수,카드_여행사_이용건수,카드_체험_이용건수,카드_주말_이용건수,카드_평일_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1.980451e+10,224267.0,14697.0,4360.0,185992.0,59.0,19159.0,76667.0,147600.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,1.796474e+10,222954.0,7338.0,12.0,173540.0,41870.0,194.0,76115.0,146839.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,3.487003e+09,57697.0,1289.0,2895.0,52897.0,90.0,526.0,18355.0,39342.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,9.269621e+09,94291.0,9103.0,271.0,80647.0,3234.0,1036.0,26654.0,67637.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,1.665746e+10,253596.0,6132.0,69282.0,145186.0,598.0,32398.0,81787.0,171809.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,7.523614e+09,112702.0,4615.0,78.0,48779.0,9.0,59221.0,39245.0,73457.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,2.207701e+09,24262.0,237.0,324.0,5929.0,NaN,17772.0,8244.0,16018.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,9.956213e+08,16319.0,179.0,10.0,15872.0,NaN,258.0,4631.0,11688.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,7.753994e+09,148677.0,21861.0,1261.0,110585.0,394.0,14576.0,48286.0,100391.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,6.209599e+09,119172.0,2310.0,291.0,93014.0,28.0,23529.0,51726.0,67446.0

In [91]:
df_age_60.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/df_60대.pkl')