## import library & load Data

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Mounted at /content/drive

In [2]:
df = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/전처리/total_data.pkl')

In [3]:
# 1. 관광 , 휴양 여행 경험하지 않은 데이터 제거
df = df[(df['MON_EXP_1']=='예') | (df['MON_EXP_2']=='예')].reset_index(drop=True)
df

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,MON_EXP_1,MON_EXP_2,MON_EXP_3,MON_EXP_4,...,국내_여행방문지_기타당일1,국내_여행방문지_기타당일2,국내_여행방문지_기타당일3,국내_여행방문지_기타당일4,국내_여행방문지_기타당일5,국내_여행방문지_기타당일6,국내_여행방문지_기타당일7,국내_여행방문지_기타당일8,국내_여행방문지_기타당일9,국내_여행방문지_기타당일10
0,11010550211_277569,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010550211_277572,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010550211_277588,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010550211_277594,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010550211_277596,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21647,3902059082A_428690,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21648,3902059082A_428729,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21649,3902059083A_580645,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21650,3902059083A_580647,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21651,3902059083A_580914,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 1 ~ 6차 여행 concat
+ 지역 별 인당 지출 액, 평균 숙박 일 수

In [6]:
# 2. 여행 1차 ~ 6차 concat 시키기
# D_TRA1_CASE : 여행형태
# D_TRA1_1_SPOT : 여행지역
# D_TRA1_ONE_COST : 인당 비용

# WT_DOM : 가중치 -> 모집단에 대한 표본조사 가중치로 여행객 수에 곱함
col_tra1 = ['ID'] + ['D_TRA1_CASE','D_TRA1_1_SPOT','D_TRA1_ONE_COST', 'WT_DOM']
tra1 = df[col_tra1]
tra1

,ID,D_TRA1_CASE,D_TRA1_1_SPOT,D_TRA1_ONE_COST,WT_DOM
0,11010550211_277569,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 삼척시,160000.0,50401.776540
1,11010550211_277572,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 서귀포시,1000000.0,98458.630392
2,11010550211_277588,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,133333.0,14950.249479
3,11010550211_277594,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,200001.0,12522.925376
4,11010550211_277596,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 춘천시,50000.0,17396.680633
...,...,...,...,...,...
21647,3902059082A_428690,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,150000.0,3406.506288
21648,3902059082A_428729,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",서울특별시 구로구,200000.0,4630.513230
21649,3902059083A_580645,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,20000.0,3984.742345
21650,3902059083A_580647,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,40000.0,3629.251100
21651,3902059083A_580914,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,40000.0,2316.305155

In [7]:
# 2차 여행 관련 컬럼 뽑고 데이터프레임 생성
col_tra2 = ['ID'] + ['D_TRA2_CASE','D_TRA2_1_SPOT','D_TRA2_ONE_COST','WT_DOM']
tra2 = df[col_tra2]

# 3차 여행 관련 컬럼 뽑고 데이터프레임 생성
col_tra3 = ['ID'] + ['D_TRA3_CASE','D_TRA3_1_SPOT','D_TRA3_ONE_COST','WT_DOM']
tra3 = df[col_tra3]

# 4차 여행 관련 컬럼 뽑고 데이터프레임 생성
col_tra4 = ['ID'] + ['D_TRA4_CASE','D_TRA4_1_SPOT','D_TRA4_ONE_COST','WT_DOM']
tra4 =df[col_tra4]

# 5차 여행 관련 컬럼 뽑고 데이터프레임 생성
col_tra5 = ['ID'] + ['D_TRA5_CASE','D_TRA5_1_SPOT','D_TRA5_ONE_COST','WT_DOM']
tra5 = df[col_tra5]

# 6차 여행 관련 컬럼 뽑고 데이터프레임 생성
col_tra6 = ['ID'] + ['D_TRA6_CASE','D_TRA6_1_SPOT','D_TRA6_ONE_COST','WT_DOM']
tra6 = df[col_tra6]

In [8]:
print(tra1.shape)
print(tra2.shape)
print(tra3.shape)
print(tra4.shape)
print(tra5.shape)
print(tra6.shape)

(21652, 5)
(21652, 5)
(21652, 5)
(21652, 5)
(21652, 5)
(21652, 5)

In [9]:
column_name = tra1.columns.tolist()

In [10]:
# concat을 위해 컬럼명 우선 일치시키기
tra1.columns = [list(range(5))]
tra2.columns = [list(range(5))]
tra3.columns = [list(range(5))]
tra4.columns = [list(range(5))]
tra5.columns = [list(range(5))]
tra6.columns = [list(range(5))]

In [11]:
concat_df = pd.concat([tra1, tra2, tra3, tra4, tra5, tra6], ignore_index=True)
concat_df

,0,1,2,3,4
0,11010550211_277569,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 삼척시,160000.0,50401.776540
1,11010550211_277572,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 서귀포시,1000000.0,98458.630392
2,11010550211_277588,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,133333.0,14950.249479
3,11010550211_277594,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,200001.0,12522.925376
4,11010550211_277596,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 춘천시,50000.0,17396.680633
...,...,...,...,...,...
129907,3902059082A_428690,NaN,NaN,NaN,3406.506288
129908,3902059082A_428729,NaN,NaN,NaN,4630.513230
129909,3902059083A_580645,NaN,NaN,NaN,3984.742345
129910,3902059083A_580647,NaN,NaN,NaN,3629.251100
129911,3902059083A_580914,NaN,NaN,NaN,2316.305155

In [12]:
# 열 이름 변경
concat_df.columns = ['ID', '여행형태', '지역', '인당비용', '가중치']

In [13]:
# 여행형태 정보가 NULL 인 행 제거
concat_df = concat_df[concat_df.iloc[:,1].notnull()].reset_index(drop=True)
concat_df

,ID,여행형태,지역,인당비용,가중치
0,11010550211_277569,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 삼척시,160000.0,50401.776540
1,11010550211_277572,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 서귀포시,1000000.0,98458.630392
2,11010550211_277588,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,133333.0,14950.249479
3,11010550211_277594,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,200001.0,12522.925376
4,11010550211_277596,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 춘천시,50000.0,17396.680633
...,...,...,...,...,...
22942,37040510351_375069,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",경상북도 성주군,60000.0,8324.011291
22943,2901062095A_286814,국내 단순 가족/친지/친구 방문 - 관광/휴양 활동이 포함되지 않음,인천광역시 부평구,150000.0,2355.545332
22944,3103066323A_514924,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",충청북도 제천시,90000.0,12819.854123
22945,3333011099A_353575,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",충청남도 서천군,50000.0,5040.763942
22946,37020121491_298787,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",경상북도 영천시,13333.0,7885.212816

In [14]:
# 관광 휴양 여행 아닌 행 제거
concat_df = concat_df[(concat_df['여행형태'] == '국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)') | (concat_df['여행형태'] == '국내 가족/친지/친구 방문 여행 - 관광/휴양 활동 포함') |  (concat_df['여행형태'] == '국내 출장/업무 여행 - 관광/휴양 활동 포함') ].reset_index(drop=True)
concat_df

,ID,여행형태,지역,인당비용,가중치
0,11010550211_277569,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 삼척시,160000.0,50401.776540
1,11010550211_277572,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 서귀포시,1000000.0,98458.630392
2,11010550211_277588,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,133333.0,14950.249479
3,11010550211_277594,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,200001.0,12522.925376
4,11010550211_277596,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 춘천시,50000.0,17396.680633
...,...,...,...,...,...
22222,37020121491_298787,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",경상북도 청송군,16667.0,7885.212816
22223,37040510351_375069,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",경상북도 성주군,60000.0,8324.011291
22224,3103066323A_514924,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",충청북도 제천시,90000.0,12819.854123
22225,3333011099A_353575,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",충청남도 서천군,50000.0,5040.763942
22226,37020121491_298787,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",경상북도 영천시,13333.0,7885.212816

In [15]:
# 여행 형태와 ID 열 제거
data = concat_df.iloc[:,2:]
data

                 지역       인당비용           가중치
0           강원도 삼척시   160000.0  50401.776540
1      제주특별자치도 서귀포시  1000000.0  98458.630392
2           강원도 강릉시   133333.0  14950.249479
3           강원도 강릉시   200001.0  12522.925376
4           강원도 춘천시    50000.0  17396.680633
...             ...        ...           ...
22222      경상북도 청송군    16667.0   7885.212816
22223      경상북도 성주군    60000.0   8324.011291
22224      충청북도 제천시    90000.0  12819.854123
22225      충청남도 서천군    50000.0   5040.763942
22226      경상북도 영천시    13333.0   7885.212816

[22227 rows x 3 columns]

## 지역 중 농촌 관광지 지역에 포함되는 지역만 필터링

In [17]:
df = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/농촌관광지df생성.pkl')
df

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0
...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0

In [18]:
시군구_농촌 = df['관광지역_시군구'].values.tolist()

In [19]:
for idx in range(len(data['지역'])):
  if len(data['지역'][idx].split(" ")[0]) != 4:
    data['지역'][idx] = data['지역'][idx].split(" ")[0][0:2] + " " + data['지역'][idx].split(" ")[1]
  #elif len(data['지역'][idx].split(" ")[0]) == 4:
  else:
    data['지역'][idx] = data['지역'][idx].split(" ")[0][0] + data['지역'][idx].split(" ")[0][2] + " " + data['지역'][idx].split(" ")[1]

<ipython-input-19-c4cd9cea7ae9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['지역'][idx] = data['지역'][idx].split(" ")[0][0:2] + " " + data['지역'][idx].split(" ")[1]
<ipython-input-19-c4cd9cea7ae9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['지역'][idx] = data['지역'][idx].split(" ")[0][0] + data['지역'][idx].split(" ")[0][2] + " " + data['지역'][idx].split(" ")[1]

In [20]:
data_농촌 = data[data['지역'].isin(시군구_농촌)].reset_index(drop = True)
data_농촌

            지역       인당비용           가중치
0       강원 삼척시   160000.0  50401.776540
1      제주 서귀포시  1000000.0  98458.630392
2       강원 강릉시   133333.0  14950.249479
3       강원 강릉시   200001.0  12522.925376
4       강원 춘천시    50000.0  17396.680633
...        ...        ...           ...
17900   경북 청송군    16667.0   7885.212816
17901   경북 성주군    60000.0   8324.011291
17902   충북 제천시    90000.0  12819.854123
17903   충남 서천군    50000.0   5040.763942
17904   경북 영천시    13333.0   7885.212816

[17905 rows x 3 columns]

## 집계 함수를 통해 지역별 데이터프레임 생성

### 여행객 수

In [21]:
지역별_여행객수 = pd.DataFrame(data_농촌.groupby(['지역'])['가중치'].sum().round(1))
지역별_여행객수.columns = ['여행객수']
지역별_여행객수

             여행객수
지역
강원 강릉시  7312582.8
강원 고성군  1021987.9
강원 동해시  1179949.5
강원 삼척시  1637981.3
강원 속초시  5271753.4
...           ...
충북 제천시  1578259.0
충북 증평군   110215.8
충북 진천군   254616.7
충북 청주시   986686.2
충북 충주시   972803.9

[142 rows x 1 columns]

### 평균인당비용

In [23]:
지역별_평균인당비용 = pd.DataFrame(data_농촌.groupby(['지역'])['인당비용'].agg(lambda x: int(x.mean())))
지역별_평균인당비용.columns = ['평균인당비용']
지역별_평균인당비용

        평균인당비용
지역
강원 강릉시  160474
강원 고성군  163526
강원 동해시  126167
강원 삼척시  139689
강원 속초시  174524
...        ...
충북 제천시  109573
충북 증평군   81672
충북 진천군   71794
충북 청주시   81015
충북 충주시   96727

[142 rows x 1 columns]

In [88]:
국민여행조사_data = pd.concat([지역별_평균인당비용,지역별_여행객수], axis = 1)
국민여행조사_data

        평균인당비용       여행객수
지역
강원 강릉시  160474  7312582.8
강원 고성군  163526  1021987.9
강원 동해시  126167  1179949.5
강원 삼척시  139689  1637981.3
강원 속초시  174524  5271753.4
...        ...        ...
충북 제천시  109573  1578259.0
충북 증평군   81672   110215.8
충북 진천군   71794   254616.7
충북 청주시   81015   986686.2
충북 충주시   96727   972803.9

[142 rows x 2 columns]

## 만족도/재방문의사/타인추천의도 열 생성

In [24]:
df = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/전처리/total_data.pkl')
df = df[(df['MON_EXP_1']=='예') | (df['MON_EXP_2']=='예')].reset_index(drop=True)
df

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,MON_EXP_1,MON_EXP_2,MON_EXP_3,MON_EXP_4,...,국내_여행방문지_기타당일1,국내_여행방문지_기타당일2,국내_여행방문지_기타당일3,국내_여행방문지_기타당일4,국내_여행방문지_기타당일5,국내_여행방문지_기타당일6,국내_여행방문지_기타당일7,국내_여행방문지_기타당일8,국내_여행방문지_기타당일9,국내_여행방문지_기타당일10
0,11010550211_277569,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010550211_277572,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010550211_277588,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010550211_277594,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010550211_277596,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21647,3902059082A_428690,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21648,3902059082A_428729,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21649,3902059083A_580645,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21650,3902059083A_580647,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21651,3902059083A_580914,1.0,0.0,0.0,0.0,0.0,예,아니오,아니오,아니오,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
recent_data = pd.DataFrame()

In [26]:
# 만족도/재방문의사/타인추천의도 는 최근 여행으로만 조사됨
# 최근 여행 데이터프레임 생성
for idx in range(len(df)):
  if pd.isna(df['D_TRA6_1_SPOT'][idx]) == True :
    if pd.isna(df['D_TRA5_1_SPOT'][idx]) == True :
      if pd.isna(df['D_TRA4_1_SPOT'][idx]) == True :
        if pd.isna(df['D_TRA3_1_SPOT'][idx]) == True :
          if pd.isna(df['D_TRA2_1_SPOT'][idx]) == True :
            if pd.isna(df['D_TRA1_1_SPOT'][idx]) == True :
              continue
            else:
              recent_data.loc[idx,['여행형태']] = df.loc[idx,['D_TRA1_CASE']].tolist()
              recent_data.loc[idx,['지역']]  = df.loc[idx,['D_TRA1_1_SPOT']].tolist()
          else:
            recent_data.loc[idx,['여행형태']] = df.loc[idx,['D_TRA2_CASE']].tolist()
            recent_data.loc[idx,['지역']] = df.loc[idx,['D_TRA2_1_SPOT']].tolist()
        else:
          recent_data.loc[idx,['여행형태']] = df.loc[idx,['D_TRA3_CASE']].tolist()
          recent_data.loc[idx,['지역']] = df.loc[idx,['D_TRA3_1_SPOT']].tolist()
      else:
        recent_data.loc[idx,['여행형태']] = df.loc[idx,['D_TRA4_CASE']].tolist()
        recent_data.loc[idx,['지역']] = df.loc[idx,['D_TRA4_1_SPOT']].tolist()
    else:
      recent_data.loc[idx,['여행형태']] = df.loc[idx,['D_TRA5_CASE']].tolist()
      recent_data.loc[idx,['지역']] = df.loc[idx,['D_TRA5_1_SPOT']].tolist()
  else:
    recent_data.loc[idx,['여행형태']] = df.loc[idx,['D_TRA5_CASE']].tolist()
    recent_data.loc[idx,['지역']] = df.loc[idx,['D_TRA5_1_SPOT']].tolist()

recent_data

                                                    여행형태            지역
0      국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)       강원도 삼척시
1      국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)  제주특별자치도 서귀포시
2      국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)       강원도 강릉시
3      국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)       강원도 강릉시
4      국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)       강원도 춘천시
...                                                  ...           ...
21647  국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)   제주특별자치도 제주시
21648  국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)     서울특별시 구로구
21649  국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)   제주특별자치도 제주시
21650  국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)   제주특별자치도 제주시
21651  국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)   제주특별자치도 제주시

[21652 rows x 2 columns]

### 만족도 변수 뽑기

In [70]:
# A10A_1 : 자연경관
# A10A_2 : 문화유산
# A10A_3 : 교통
# A10A_4 : 숙박시설
# A10A_5 : 식당 및 음식
# A10A_6 : 쇼핑
# A10A_8 : 관광지 편의시설
# A10A_9 : 지역 관광종사자의 친절성
# A10A_10 : 체험프로그램
# A10A_11 : 관광지 물가
# A10A_12 : 관광지 혼잡도
# A11 : 재방문의도
# A12 : 타인추천의도
# BAGE : 연령대

In [72]:
satis_data = df.loc[:, ['A10A_1','A10A_2','A10A_3','A10A_4','A10A_5','A10A_6','A10A_8','A10A_9','A10A_10','A10A_11','A10A_12','A11','A12']]
satis_data

,A10A_1,A10A_2,A10A_3,A10A_4,A10A_5,A10A_6,A10A_8,A10A_9,A10A_10,A10A_11,A10A_12,A11,A12
0,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,④ 높음
1,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,③ 보통,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
2,⑤ 매우 만족,④ 만족,④ 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,④ 만족,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,④ 높음
3,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,③ 보통,④ 만족,⑤ 매우 높음,④ 높음
4,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,③ 보통
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21647,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
21648,⑤ 매우 만족,⑤ 매우 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,② 불만족,③ 보통,④ 높음,④ 높음
21649,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,NaN,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,경험 해보지 못함,④ 만족,⑤ 매우 높음,⑤ 매우 높음
21650,④ 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,③ 보통,경험 해보지 못함,③ 보통,④ 만족,④ 높음,④ 높음
21651,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,④ 만족,경험 해보지 못함,④ 만족,③ 보통,④ 높음,④ 높음

In [74]:
satisfy_data = pd.concat([recent_data, satis_data], axis = 1)
satisfy_data

,여행형태,지역,A10A_1,A10A_2,A10A_3,A10A_4,A10A_5,A10A_6,A10A_8,A10A_9,A10A_10,A10A_11,A10A_12,A11,A12
0,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 삼척시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,④ 높음
1,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 서귀포시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,③ 보통,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
2,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,⑤ 매우 만족,④ 만족,④ 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,④ 만족,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,④ 높음
3,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,③ 보통,④ 만족,⑤ 매우 높음,④ 높음
4,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 춘천시,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,③ 보통
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21647,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
21648,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",서울특별시 구로구,⑤ 매우 만족,⑤ 매우 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,② 불만족,③ 보통,④ 높음,④ 높음
21649,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,NaN,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,경험 해보지 못함,④ 만족,⑤ 매우 높음,⑤ 매우 높음
21650,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,④ 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,③ 보통,경험 해보지 못함,③ 보통,④ 만족,④ 높음,④ 높음
21651,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,④ 만족,경험 해보지 못함,④ 만족,③ 보통,④ 높음,④ 높음

In [75]:
# 관광 휴양 여행 아닌 행 제거
satisfy_data = satisfy_data[(satisfy_data['여행형태'] == '국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)') | (satisfy_data['여행형태'] == '국내 가족/친지/친구 방문 여행 - 관광/휴양 활동 포함') |  (satisfy_data['여행형태'] == '국내 출장/업무 여행 - 관광/휴양 활동 포함') ].reset_index(drop=True)
satisfy_data

,여행형태,지역,A10A_1,A10A_2,A10A_3,A10A_4,A10A_5,A10A_6,A10A_8,A10A_9,A10A_10,A10A_11,A10A_12,A11,A12
0,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 삼척시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,④ 높음
1,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 서귀포시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,③ 보통,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
2,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,⑤ 매우 만족,④ 만족,④ 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,④ 만족,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,④ 높음
3,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 강릉시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,③ 보통,④ 만족,⑤ 매우 높음,④ 높음
4,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",강원도 춘천시,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,③ 보통
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21294,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
21295,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",서울특별시 구로구,⑤ 매우 만족,⑤ 매우 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,② 불만족,③ 보통,④ 높음,④ 높음
21296,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,NaN,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,경험 해보지 못함,④ 만족,⑤ 매우 높음,⑤ 매우 높음
21297,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,④ 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,③ 보통,경험 해보지 못함,③ 보통,④ 만족,④ 높음,④ 높음
21298,"국내 관광/휴양 여행(가족/친지/친구 방문, 출장/업무 활동 없는 단순 관광/휴양 여행)",제주특별자치도 제주시,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,④ 만족,경험 해보지 못함,④ 만족,③ 보통,④ 높음,④ 높음

In [76]:
# 여행 형태 열 제거
data = satisfy_data.iloc[:,1:]
data.columns = ['지역','자연경관','문화유산','교통','숙박시설','식당및음식','쇼핑','관광지편의시설','관광종사자의친절성','체험프로그램','관광지물가','관광지혼잡도', '재방문의도','타인추천의도']
data

,지역,자연경관,문화유산,교통,숙박시설,식당및음식,쇼핑,관광지편의시설,관광종사자의친절성,체험프로그램,관광지물가,관광지혼잡도,재방문의도,타인추천의도
0,강원도 삼척시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,④ 높음
1,제주특별자치도 서귀포시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,③ 보통,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
2,강원도 강릉시,⑤ 매우 만족,④ 만족,④ 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,④ 만족,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,④ 높음
3,강원도 강릉시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,③ 보통,④ 만족,⑤ 매우 높음,④ 높음
4,강원도 춘천시,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,③ 보통
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21294,제주특별자치도 제주시,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
21295,서울특별시 구로구,⑤ 매우 만족,⑤ 매우 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,② 불만족,③ 보통,④ 높음,④ 높음
21296,제주특별자치도 제주시,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,NaN,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,경험 해보지 못함,④ 만족,⑤ 매우 높음,⑤ 매우 높음
21297,제주특별자치도 제주시,④ 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,③ 보통,경험 해보지 못함,③ 보통,④ 만족,④ 높음,④ 높음
21298,제주특별자치도 제주시,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,④ 만족,경험 해보지 못함,④ 만족,③ 보통,④ 높음,④ 높음

### 농촌관광지 데이터의 지역만 필터링

In [77]:
for idx in range(len(data['지역'])):
  if len(data['지역'][idx].split(" ")[0]) != 4:
    data['지역'][idx] = data['지역'][idx].split(" ")[0][0:2] + " " + data['지역'][idx].split(" ")[1]
  #elif len(data['지역'][idx].split(" ")[0]) == 4:
  else:
    data['지역'][idx] = data['지역'][idx].split(" ")[0][0] + data['지역'][idx].split(" ")[0][2] + " " + data['지역'][idx].split(" ")[1]

<ipython-input-77-c4cd9cea7ae9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['지역'][idx] = data['지역'][idx].split(" ")[0][0:2] + " " + data['지역'][idx].split(" ")[1]
<ipython-input-77-c4cd9cea7ae9>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['지역'][idx] = data['지역'][idx].split(" ")[0][0] + data['지역'][idx].split(" ")[0][2] + " " + data['지역'][idx].split(" ")[1]

In [78]:
data_농촌 = data[data['지역'].isin(시군구_농촌)].reset_index(drop=True)
data_농촌

,지역,자연경관,문화유산,교통,숙박시설,식당및음식,쇼핑,관광지편의시설,관광종사자의친절성,체험프로그램,관광지물가,관광지혼잡도,재방문의도,타인추천의도
0,강원 삼척시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,④ 높음
1,제주 서귀포시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,④ 만족,③ 보통,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
2,강원 강릉시,⑤ 매우 만족,④ 만족,④ 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,④ 만족,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,⑤ 매우 높음,④ 높음
3,강원 강릉시,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,⑤ 매우 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,③ 보통,④ 만족,⑤ 매우 높음,④ 높음
4,강원 춘천시,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,④ 만족,④ 만족,④ 만족,경험 해보지 못함,④ 만족,④ 만족,④ 높음,③ 보통
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17178,경북 경주시,③ 보통,④ 만족,⑤ 매우 만족,④ 만족,⑤ 매우 만족,⑤ 매우 만족,④ 만족,③ 보통,경험 해보지 못함,④ 만족,④ 만족,④ 높음,④ 높음
17179,제주 제주시,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,경험 해보지 못함,④ 만족,④ 만족,④ 만족,⑤ 매우 높음,⑤ 매우 높음
17180,제주 제주시,⑤ 매우 만족,⑤ 매우 만족,⑤ 매우 만족,NaN,⑤ 매우 만족,경험 해보지 못함,⑤ 매우 만족,⑤ 매우 만족,경험 해보지 못함,경험 해보지 못함,④ 만족,⑤ 매우 높음,⑤ 매우 높음
17181,제주 제주시,④ 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,③ 보통,경험 해보지 못함,③ 보통,④ 만족,④ 높음,④ 높음
17182,제주 제주시,⑤ 매우 만족,④ 만족,④ 만족,NaN,④ 만족,경험 해보지 못함,④ 만족,④ 만족,경험 해보지 못함,④ 만족,③ 보통,④ 높음,④ 높음

### 카테고리 변수 숫자로 변환

In [79]:
# 데이터를 문자열 형태로 바꿈
for col in data_농촌.columns[1:]:
  data_농촌[col] = data_농촌[col].astype('str')

In [80]:
for col in data_농촌.columns[1:]:
  print(col, data_농촌[col].unique())

자연경관 ['⑤ 매우 만족' '④ 만족' '경험 해보지 못함' '③ 보통' '① 매우 불만족' '② 불만족' 'nan']
문화유산 ['④ 만족' '경험 해보지 못함' '⑤ 매우 만족' '③ 보통' '② 불만족' 'nan']
교통 ['④ 만족' '⑤ 매우 만족' '③ 보통' '경험 해보지 못함' '② 불만족' '① 매우 불만족' 'nan']
숙박시설 ['④ 만족' '⑤ 매우 만족' 'nan' '③ 보통' '② 불만족']
식당및음식 ['④ 만족' '⑤ 매우 만족' '경험 해보지 못함' '③ 보통' '② 불만족' '① 매우 불만족' 'nan']
쇼핑 ['④ 만족' '③ 보통' '⑤ 매우 만족' '경험 해보지 못함' '② 불만족' 'nan']
관광지편의시설 ['④ 만족' '⑤ 매우 만족' '경험 해보지 못함' '③ 보통' '② 불만족' '① 매우 불만족' 'nan']
관광종사자의친절성 ['④ 만족' '⑤ 매우 만족' '③ 보통' '경험 해보지 못함' '② 불만족' '① 매우 불만족' 'nan']
체험프로그램 ['경험 해보지 못함' '⑤ 매우 만족' '④ 만족' '③ 보통' '② 불만족' 'nan']
관광지물가 ['④ 만족' '③ 보통' '⑤ 매우 만족' '경험 해보지 못함' '② 불만족' '① 매우 불만족' 'nan']
관광지혼잡도 ['④ 만족' '③ 보통' '경험 해보지 못함' '⑤ 매우 만족' '② 불만족' '① 매우 불만족' 'nan']
재방문의도 ['④ 높음' '⑤ 매우 높음' '③ 보통' '② 낮음' 'nan']
타인추천의도 ['④ 높음' '⑤ 매우 높음' '③ 보통' '② 낮음' 'nan' '① 매우 낮음']

In [81]:
for col in data_농촌.columns[1:12]:
  for idx in range(len(data_농촌.index)):
    if data_농촌[col][idx] == '⑤ 매우 만족':
      data_농촌[col][idx] = 5
    elif data_농촌[col][idx] == '④ 만족' :
      data_농촌[col][idx] = 4
    elif data_농촌[col][idx] == '③ 보통' :
      data_농촌[col][idx] = 3
    elif data_농촌[col][idx] == '② 불만족' :
      data_농촌[col][idx] = 2
    elif data_농촌[col][idx] == '① 매우 불만족' :
      data_농촌[col][idx] = 1
    else:
      data_농촌[col][idx] = np.nan

In [82]:
for col in data_농촌.columns[12:]:
  for idx in range(len(data_농촌.index)):
    if data_농촌[col][idx] == '⑤ 매우 높음':
      data_농촌[col][idx] = 5
    elif data_농촌[col][idx] == '④ 높음' :
      data_농촌[col][idx] = 4
    elif data_농촌[col][idx] == '③ 보통' :
      data_농촌[col][idx] = 3
    elif data_농촌[col][idx] == '② 낮음' :
      data_농촌[col][idx] = 2
    elif data_농촌[col][idx] == '① 매우 낮음' :
      data_농촌[col][idx] = 1
    else:
      data_농촌[col][idx] = np.nan

In [83]:
for col in data_농촌.columns[1:]:
  print(col, data_농촌[col].unique())

자연경관 [5 4 nan 3 1 2]
문화유산 [4 nan 5 3 2]
교통 [4 5 3 nan 2 1]
숙박시설 [4 5 nan 3 2]
식당및음식 [4 5 nan 3 2 1]
쇼핑 [4 3 5 nan 2]
관광지편의시설 [4 5 nan 3 2 1]
관광종사자의친절성 [4 5 3 nan 2 1]
체험프로그램 [nan 5 4 3 2]
관광지물가 [4 3 5 nan 2 1]
관광지혼잡도 [4 3 nan 5 2 1]
재방문의도 [4 5 3 2 nan]

In [85]:
data_농촌

,지역,자연경관,문화유산,교통,숙박시설,식당및음식,쇼핑,관광지편의시설,관광종사자의친절성,체험프로그램,관광지물가,관광지혼잡도,재방문의도,타인추천의도
0,강원 삼척시,5,4,4,4,4,4,4,4,NaN,4,4,4,4
1,제주 서귀포시,5,4,4,4,4,3,4,4,NaN,4,4,5,5
2,강원 강릉시,5,4,4,5,5,5,4,5,NaN,4,4,5,4
3,강원 강릉시,5,4,4,4,5,4,4,4,NaN,3,4,5,4
4,강원 춘천시,5,4,4,NaN,4,4,4,4,NaN,4,4,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17178,경북 경주시,3,4,5,4,5,5,4,3,NaN,4,4,4,4
17179,제주 제주시,5,5,5,5,5,NaN,5,NaN,4,4,4,5,5
17180,제주 제주시,5,5,5,NaN,5,NaN,5,5,NaN,NaN,4,5,5
17181,제주 제주시,4,4,4,NaN,4,NaN,4,3,NaN,3,4,4,4
17182,제주 제주시,5,4,4,NaN,4,NaN,4,4,NaN,4,3,4,4

### 지역별로 평균

In [86]:
# 컬럼별 값을 더하고 na를 제외한 값의 개수로 나눠 평균을 구했음
def NaMean(x):
  return x.sum() / x.count()

In [87]:
# 컬럼별로 위 함수 적용
지역별_만족도 = data_농촌.groupby('지역')[data_농촌.columns[1:]].agg(NaMean)
지역별_만족도 = round(지역별_만족도,2)
지역별_만족도

<ipython-input-86-7d802b6befb0>:3: RuntimeWarning: invalid value encountered in long_scalars
  return x.sum() / x.count()

,자연경관,문화유산,교통,숙박시설,식당및음식,쇼핑,관광지편의시설,관광종사자의친절성,체험프로그램,관광지물가,관광지혼잡도,재방문의도,타인추천의도
지역,,,,,,,,,,,,,
강원 강릉시,4.56,4.24,4.19,4.29,4.24,4.16,4.19,4.19,4.26,3.80,3.94,4.12,4.01
강원 고성군,4.54,4.15,4.26,4.16,4.24,4.14,4.19,4.18,4.14,3.81,4.01,4.10,4.08
강원 동해시,4.48,4.17,4.11,4.30,4.22,4.06,4.22,4.08,3.93,3.78,4.13,4.00,3.92
강원 삼척시,4.63,4.47,4.33,4.29,4.30,4.16,4.32,4.23,4.23,3.88,4.15,4.16,4.03
강원 속초시,4.49,4.28,4.16,4.34,4.24,4.15,4.18,4.16,4.23,3.86,4.02,4.07,4.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
충북 제천시,4.53,4.41,4.14,4.49,4.21,4.20,4.24,4.23,4.24,4.01,4.12,4.08,4.04
충북 증평군,4.43,4.90,4.27,4.14,4.20,4.00,4.36,4.29,4.33,3.71,4.27,4.00,4.00
충북 진천군,4.26,4.04,4.13,4.25,4.10,3.86,4.07,4.04,4.29,3.93,3.97,4.13,4.03
충북 청주시,4.30,4.12,4.13,4.25,4.18,4.14,4.13,4.21,4.16,3.88,4.02,3.95,3.85
충북 충주시,4.47,4.25,4.26,4.08,4.25,4.18,4.24,4.33,4.27,4.00,4.12,4.12,4.02

## 데이터프레임 합치기

In [89]:
국민여행조사_data

        평균인당비용       여행객수
지역
강원 강릉시  160474  7312582.8
강원 고성군  163526  1021987.9
강원 동해시  126167  1179949.5
강원 삼척시  139689  1637981.3
강원 속초시  174524  5271753.4
...        ...        ...
충북 제천시  109573  1578259.0
충북 증평군   81672   110215.8
충북 진천군   71794   254616.7
충북 청주시   81015   986686.2
충북 충주시   96727   972803.9

[142 rows x 2 columns]

In [90]:
지역별_만족도

,자연경관,문화유산,교통,숙박시설,식당및음식,쇼핑,관광지편의시설,관광종사자의친절성,체험프로그램,관광지물가,관광지혼잡도,재방문의도,타인추천의도
지역,,,,,,,,,,,,,
강원 강릉시,4.56,4.24,4.19,4.29,4.24,4.16,4.19,4.19,4.26,3.80,3.94,4.12,4.01
강원 고성군,4.54,4.15,4.26,4.16,4.24,4.14,4.19,4.18,4.14,3.81,4.01,4.10,4.08
강원 동해시,4.48,4.17,4.11,4.30,4.22,4.06,4.22,4.08,3.93,3.78,4.13,4.00,3.92
강원 삼척시,4.63,4.47,4.33,4.29,4.30,4.16,4.32,4.23,4.23,3.88,4.15,4.16,4.03
강원 속초시,4.49,4.28,4.16,4.34,4.24,4.15,4.18,4.16,4.23,3.86,4.02,4.07,4.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
충북 제천시,4.53,4.41,4.14,4.49,4.21,4.20,4.24,4.23,4.24,4.01,4.12,4.08,4.04
충북 증평군,4.43,4.90,4.27,4.14,4.20,4.00,4.36,4.29,4.33,3.71,4.27,4.00,4.00
충북 진천군,4.26,4.04,4.13,4.25,4.10,3.86,4.07,4.04,4.29,3.93,3.97,4.13,4.03
충북 청주시,4.30,4.12,4.13,4.25,4.18,4.14,4.13,4.21,4.16,3.88,4.02,3.95,3.85
충북 충주시,4.47,4.25,4.26,4.08,4.25,4.18,4.24,4.33,4.27,4.00,4.12,4.12,4.02

In [92]:
국민여행조사_data = pd.merge(지역별_만족도 , 국민여행조사_data, how = 'left', left_on = '지역', right_on = '지역')
국민여행조사_data

,자연경관,문화유산,교통,숙박시설,식당및음식,쇼핑,관광지편의시설,관광종사자의친절성,체험프로그램,관광지물가,관광지혼잡도,재방문의도,타인추천의도,평균인당비용,여행객수
지역,,,,,,,,,,,,,,,
강원 강릉시,4.56,4.24,4.19,4.29,4.24,4.16,4.19,4.19,4.26,3.80,3.94,4.12,4.01,160474,7312582.8
강원 고성군,4.54,4.15,4.26,4.16,4.24,4.14,4.19,4.18,4.14,3.81,4.01,4.10,4.08,163526,1021987.9
강원 동해시,4.48,4.17,4.11,4.30,4.22,4.06,4.22,4.08,3.93,3.78,4.13,4.00,3.92,126167,1179949.5
강원 삼척시,4.63,4.47,4.33,4.29,4.30,4.16,4.32,4.23,4.23,3.88,4.15,4.16,4.03,139689,1637981.3
강원 속초시,4.49,4.28,4.16,4.34,4.24,4.15,4.18,4.16,4.23,3.86,4.02,4.07,4.04,174524,5271753.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
충북 제천시,4.53,4.41,4.14,4.49,4.21,4.20,4.24,4.23,4.24,4.01,4.12,4.08,4.04,109573,1578259.0
충북 증평군,4.43,4.90,4.27,4.14,4.20,4.00,4.36,4.29,4.33,3.71,4.27,4.00,4.00,81672,110215.8
충북 진천군,4.26,4.04,4.13,4.25,4.10,3.86,4.07,4.04,4.29,3.93,3.97,4.13,4.03,71794,254616.7
충북 청주시,4.30,4.12,4.13,4.25,4.18,4.14,4.13,4.21,4.16,3.88,4.02,3.95,3.85,81015,986686.2
충북 충주시,4.47,4.25,4.26,4.08,4.25,4.18,4.24,4.33,4.27,4.00,4.12,4.12,4.02,96727,972803.9

In [93]:
국민여행조사_data.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/국민여행조사data최종.pkl')

## 농촌관광지 데이터랑 국민여행조사 데이터 합치기

In [94]:
df1 = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/국민여행조사data최종.pkl')

In [95]:
df1

,자연경관,문화유산,교통,숙박시설,식당및음식,쇼핑,관광지편의시설,관광종사자의친절성,체험프로그램,관광지물가,관광지혼잡도,재방문의도,타인추천의도,평균인당비용,여행객수
지역,,,,,,,,,,,,,,,
강원 강릉시,4.56,4.24,4.19,4.29,4.24,4.16,4.19,4.19,4.26,3.80,3.94,4.12,4.01,160474,7312582.8
강원 고성군,4.54,4.15,4.26,4.16,4.24,4.14,4.19,4.18,4.14,3.81,4.01,4.10,4.08,163526,1021987.9
강원 동해시,4.48,4.17,4.11,4.30,4.22,4.06,4.22,4.08,3.93,3.78,4.13,4.00,3.92,126167,1179949.5
강원 삼척시,4.63,4.47,4.33,4.29,4.30,4.16,4.32,4.23,4.23,3.88,4.15,4.16,4.03,139689,1637981.3
강원 속초시,4.49,4.28,4.16,4.34,4.24,4.15,4.18,4.16,4.23,3.86,4.02,4.07,4.04,174524,5271753.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
충북 제천시,4.53,4.41,4.14,4.49,4.21,4.20,4.24,4.23,4.24,4.01,4.12,4.08,4.04,109573,1578259.0
충북 증평군,4.43,4.90,4.27,4.14,4.20,4.00,4.36,4.29,4.33,3.71,4.27,4.00,4.00,81672,110215.8
충북 진천군,4.26,4.04,4.13,4.25,4.10,3.86,4.07,4.04,4.29,3.93,3.97,4.13,4.03,71794,254616.7
충북 청주시,4.30,4.12,4.13,4.25,4.18,4.14,4.13,4.21,4.16,3.88,4.02,3.95,3.85,81015,986686.2
충북 충주시,4.47,4.25,4.26,4.08,4.25,4.18,4.24,4.33,4.27,4.00,4.12,4.12,4.02,96727,972803.9

In [96]:
df2 = pd.read_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/농촌관광지df2번째.pkl')
df2

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_20대_이용건수,카드_30대_이용건수,카드_40대_이용건수,카드_50대_이용건수,카드_60대_이용건수,카드_관광쇼핑_이용건수,카드_교통_이용건수,카드_숙박_이용건수,카드_여행사_이용건수,카드_체험_이용건수,카드_주말_이용건수,카드_평일_이용건수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1147478.0,1567237.0,1434881.0,990532.0,552024.0,512410.0,35587.0,4307834.0,988.0,835333.0,2415046.0,3277106.0
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,236627.0,1009571.0,1255043.0,664773.0,505690.0,86367.0,209.0,3076538.0,501002.0,7588.0,1588277.0,2083427.0
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,91003.0,163857.0,260025.0,205250.0,134194.0,23638.0,32077.0,782379.0,910.0,15325.0,328989.0,525340.0
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,143917.0,601522.0,747283.0,383051.0,241549.0,68602.0,3420.0,1996406.0,17536.0,31358.0,774949.0,1342373.0
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,481591.0,1122668.0,1345131.0,962638.0,618593.0,121180.0,983893.0,2640282.0,25579.0,759687.0,1871641.0,2658980.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,264708.0,753039.0,655702.0,373022.0,252826.0,44337.0,2556.0,654268.0,180.0,1597956.0,988239.0,1311058.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,56600.0,320735.0,256707.0,115898.0,69334.0,1660.0,3503.0,101510.0,30.0,712571.0,502978.0,316296.0
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,42046.0,75275.0,100083.0,87132.0,37515.0,1799.0,963.0,326770.0,NaN,12519.0,118280.0,223771.0
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,796993.0,826937.0,812536.0,651122.0,378616.0,127574.0,37415.0,2774910.0,2955.0,523350.0,1376495.0,2089709.0
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,209753.0,494091.0,503371.0,402461.0,293413.0,18099.0,7699.0,1143215.0,246.0,733830.0,981141.0,921948.0

In [97]:
df3 = pd.merge(df2, df1, how='left', left_on='관광지역_시군구', right_on='지역')
df3

,관광지역_시군구,농촌마을_수,농촌마을_체험_평균등급,농촌마을_교육_평균등급,농촌마을_숙박_평균등급,농촌마을_음식_평균등급,농촌마을_으뜸촌_선정수,카드_20대_이용건수,카드_30대_이용건수,카드_40대_이용건수,...,쇼핑,관광지편의시설,관광종사자의친절성,체험프로그램,관광지물가,관광지혼잡도,재방문의도,타인추천의도,평균인당비용,여행객수
0,강원 강릉시,12,1.417,2.333,1.500,1.556,0,1147478.0,1567237.0,1434881.0,...,4.16,4.19,4.19,4.26,3.80,3.94,4.12,4.01,160474.0,7312582.8
1,강원 고성군,2,2.000,3.000,2.000,2.000,0,236627.0,1009571.0,1255043.0,...,4.14,4.19,4.18,4.14,3.81,4.01,4.10,4.08,163526.0,1021987.9
2,강원 동해시,2,2.000,2.000,1.000,1.824,0,91003.0,163857.0,260025.0,...,4.06,4.22,4.08,3.93,3.78,4.13,4.00,3.92,126167.0,1179949.5
3,강원 삼척시,9,1.750,2.000,1.714,2.000,0,143917.0,601522.0,747283.0,...,4.16,4.32,4.23,4.23,3.88,4.15,4.16,4.03,139689.0,1637981.3
4,강원 속초시,1,2.000,1.996,1.860,1.824,0,481591.0,1122668.0,1345131.0,...,4.15,4.18,4.16,4.23,3.86,4.02,4.07,4.04,174524.0,5271753.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,충북 제천시,7,1.714,3.000,1.833,1.750,0,264708.0,753039.0,655702.0,...,4.20,4.24,4.23,4.24,4.01,4.12,4.08,4.04,109573.0,1578259.0
139,충북 증평군,4,2.000,2.000,2.000,1.667,0,56600.0,320735.0,256707.0,...,4.00,4.36,4.29,4.33,3.71,4.27,4.00,4.00,81672.0,110215.8
140,충북 진천군,2,1.500,1.996,1.500,2.000,0,42046.0,75275.0,100083.0,...,3.86,4.07,4.04,4.29,3.93,3.97,4.13,4.03,71794.0,254616.7
141,충북 청주시,5,2.250,2.000,2.600,3.000,0,796993.0,826937.0,812536.0,...,4.14,4.13,4.21,4.16,3.88,4.02,3.95,3.85,81015.0,986686.2
142,충북 충주시,6,2.000,2.000,2.250,2.500,0,209753.0,494091.0,503371.0,...,4.18,4.24,4.33,4.27,4.00,4.12,4.12,4.02,96727.0,972803.9

In [100]:
df3.to_pickle('/content/drive/MyDrive/문화관광 빅데이터 공모전/대참사/최종.pkl')